#+title: agridat notes

This document lists notes about data sources searched and additional sources of agricultural data.  Although this is an .org file, the formatting is best viewed in plain text mode.

* stability

* done
adugna.sorghum 28g,13l,5y
brandle.rape 5g,9l,3y
denis.missing 5g,26e
digby.jointregression 10g,17l
fan.stability 13g,10l,2y
hildebrand.systems
huehn.wheat 20g,10e 
lu.stability 5g,6e
pieopho.cocksfoot 25g,7y
williams.trees 37g,6l

* todo ?
kamidi 11g,7l
lin.balanced 33g,12l
lin.unbalanced 33g,18l

Oakey, Cullis, Thompson
http://www.g3journal.org/content/6/5/1313/suppl/DC1

** Statistical Analysis of Agricultural Experiments with R
http://rstats4ag.org/

Rothamsted Annual Reports
http://www.era.rothamsted.ac.uk/eradoc/books/1
Done: 1908-1922

Sawyer field at Rothamsted, Mentioned in McCullagh's paper. 
http://www.era.rothamsted.ac.uk/eradoc/book/84
page 154
Pages 138-153 have traditional RCB experiments.

Fairfield Smith data
http://www.stat.uchicago.edu/~pmcc/reml/


Jose Crossa papers
http://repository.cimmyt.org/xmlui/handle/10883/1/browse?value=Crossa,%20J.&type=author
Meta-r http://repository.cimmyt.org/xmlui/handle/10883/4130
Data
http://repository.cimmyt.org/xmlui/handle/10883/4036
http://repository.cimmyt.org/xmlui/handle/10883/2976
http://repository.cimmyt.org/xmlui/handle/10883/1380
http://repository.cimmyt.org/xmlui/handle/10883/4128
http://repository.cimmyt.org/xmlui/handle/10883/4290


Die Landwirtschaftlichen Versuchs-Stations
http://catalog.hathitrust.org/Record/000549685

Summary of meta-analyses
http://www6.versailles-grignon.inra.fr/agronomie/Meta-analysis-in-agronomy/References

QTL analysis using Integrated Breeding Platform.
https://www.integratedbreeding.net/165/training/bms-user-manual/qtl-analysis
CC-BY-SA license

Richard Plant
http://www.plantsciences.ucdavis.edu/plant/qgislabs.htm
CC-SA license

MapCalc
http://www.innovativegis.com/basis/
Joseph Berry.  Looks interesting, free for education.  Center pivot data.

Analyzing Precision Ag Data <-- interesting workshop
http://www.innovativegis.com/basis/Books/AnalyzingPAdata/Default.htm
http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Support_materials/Default.htm
http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Default.htm

http://www.innovativegis.com/basis/pfprimer/Appendix_D/Appendix_D.htm
http://www.innovativegis.com/basis/pfprimer/Topic4/Topic4.htm

* Papers

Biplot/StdErr/VanEeuwijk 1993 - Incorporating env info
Biplot/Bartkowiak GxE table
GE folder: Crossa 1997

Stability folder
Fan 2007 - Yield stability of maize
GxE / Flores 1998 Flores 1998 - bean & pea yields, Flores 2012, Flores 2013

Jode Edwards
Data analyzed in this report were obtained from the Iowa
State University Oat Variety Trial for the years 1997 to 2003.


** Malosetti 2013
F2 data.  Folder: GE
http://www.frontiersin.org/Plant_Physiology/10.3389/fphys.2013.00044/abstract
CC license:


** da Silva
A Bayesian Shrinkage Approach for AMMI Models
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0131414#pone-0131414-t001
CC-BY. Partial code, data.


** Perez
Comparison Between Linear and Non-parametric Regression Models for Genome-Enabled Prediction in Wheat
https://www.scienceopen.com/document/vid/4017fb51-381c-4374-93aa-608423df4004;jsessionid=0TLjjSbaooSUk1y3JKd4nUeb.master:so-app1-prd
Data:
http://www.g3journal.org/content/suppl/2012/12/05/2.12.1595.DC1
All content has CC license

** VanEeuwijk 1998.
Multiplicative Models	for	Interaction	in Three-Way ANOVA,	with Applications	to
Plant	Breeding Three-way data
http://www.jstor.org/stable/2533660

* Other
Many interesting pages.  Non-open license...?
Lecture and data
http://articles.extension.org/plant_breeding_genomics
http://articles.extension.org/pages/68660/plant-breeding-and-genomics-learning-lessons
http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar
http://articles.extension.org/pages/61006/estimating-heritability-and-blups-for-traits-using-tomato-phenotypic-data <---
http://articles.extension.org/pages/68019/genomic-relationships-and-gblup
http://pbgworks.org/node/1440

* Augmented

Jennifer Kling Lattice Design.  Data.
http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar
http://cropandsoil.oregonstate.edu/system/files/u534/Lattice_seminar.pdf
https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447275
https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447276
https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447273



* Journals

** Agronomy Journal
Skimmed Vol 1

** Biometrics. Skimmed 1947-2006
http://www.jstor.org/action/showPublication?journalCode=biometrics

** Field Crops Research. 
http://www.sciencedirect.com/science/journal/03784290/157
Vol 1-40

** IASRI newsletters
http://www.iasri.res.in/NewsLetters/nl.HTM

** JABES
Vol 6.

** Journal of the Indian Society of Agricultural Statistics
http://www.isas.org.in/jsp/onlinejournal.jsp
Skimmed: Vol 50-56

** JRSSA

** JRSSB 1940-1997
http://www.jstor.org/action/showPublication?journalCode=jroyastatsocise4
Datasets 1998-2015
http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9868/homepage/seriesb_datasets.htm
http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm

** JRSSC Applied Statistics datasets
http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm
1998-2015

** The American Statistician
Vol 1-13


* ----------------------------------------------------------------------------


* Books


** Maize International Testing 1982. CIMMYT.
http://pdf.usaid.gov/pdf_docs/PNAAQ389.pdf


** Annual report - Nebraska Agricultural Experiment Station
Vol 19-24, 1906-1911
https://books.google.com/books?id=HBlJAAAAMAAJ


** Andrews and Herzberg. Data.
http://www.stat.duke.edu/courses/Spring01/sta114/data/andrews.html
Table 2.1: agridat::darwin.maize
Table 5.1: agridat::broadbalk.wheat
Table 6.1: agridat::mercer.wheat.uniformity
Table 6.2: agridat::wiebe.wheat.uniformity
Table 58.1: agridat::caribbean.maize


** D. Bayisa (2010). Application of Spatial Mixed Model in Agricultural Field Experiment.
Master thesis. Department of Statistics, Addis Ababa University.
At least one dataset from wheat, RCB, with field coordinates.
See also http://www.ethstat.org.et/esa_publications.html, Volume 19


** Peter Diggle. Longitudinal Data Analysis.
http://www.maths.lancs.ac.uk/~diggle/lda/Datasets/

Pig weight data: SemiPar::pig.weights

Sitka spruce data: geepack::spruce

Milk protein data: nlme::Milk.  A thorough description of this data can be
found in Molenberghs & Kenward, /Missing Data in Clinical Studies/, p. 377.
Original source: A. P. Verbyla and B. R. Cullis, Modelling in Repeated
Measures Experiments. http://www.jstor.org/stable/2347384
require(latticeExtra)
xyplot(protein~Time|Diet, data=Milk, group=Cow, type='l') +
xyplot(protein~Time|Diet, data=Milk, type='smooth', lwd=2, col="black")


** Walt Federer. Analysis of intercropping experiments.


** Walt Federer, Experimental Design
192 3x3 factorial
204 3x2 factorial
236 2x2x2 factorial with confounding
257 2x3x2 factorial with confounding
276 split-plot with layout
285 nested multi-loc (Also problems page 22)
350 cubic lattice
420 balanced inc block
491 Latin square with covariate


** Federer. Variations on split-plot.


** Gomez. Statistical Procedures for Agricultural Research


** Cyril H. Goulden, Methods of Statistical Analysis

First edition: http://archive.org/details/methodsofstatist031744mbp
18 Uniformity trial: agridat::goulden.barley.uniformity
153 Split-split plot with factorial sub-plot treatment: agridat::goulden.splitsplit
194 Incomplete block
197 Inc block
205 Latin square
208 Inc block
255 Covariates in feeding trial: agridat::crampton.pig

Second edition: http://krishikosh.egranth.ac.in/handle/1/2034118
216 Latin square: agridat::goulden.latin
423 Control chart with egg weights: agridat::goulden.eggs


** Little & Hills. Agricultural Experimentation.
79 Latin square
89 Split-plot
103 Split-split
117 Split-block: agridat::little.splitblock
126 Repeated harvests


** Mead et al. The Design of Experiments.
Turnip spacing data.
https://books.google.com/books?id=CaFZPbCllrMC&pg=PA323


** Ostle. Statistics in Research, 2nd ed.
455 2 factors, 1 covariate
458 1 factor, 2 covariates: agridat::crampton.pig


** Paterson. 1939. Statistical Technique In Agricultural Research.
http://www.archive.org/details/statisticaltechn031729mbp


** Rayner. A First Course In Biometry For Agriculture Students
19/456. 2x2x4 Factorial, 2 rep
19/466. 2x4 factorial, layout, plot size, kale (from Rothamsted)
19/466. 3x5 factorial, 3 rep, potato
20/494. 3x4 Split-plot with layout
21/505. 2x2x2 Factorial, 5 rep
21/515. 2x2x2x2 Factorial, 3 rep, with layout. (Evaluated, rejected as too variable)
22/537  2x2x2 factorial, 6 rep, potato
22/537  2x2x2x2 factorial, 2 rep, wheat, layout


** Schabenberger and Francis J. Pierce. 2001
Contemporary Statistical Models for the Plant and Soil Sciences



* Classes


** Arellano
http://www.stat.ncsu.edu/people/arellano/courses/st524/Fall08/


** Hernandez
http://www.soils.umn.edu/academics/classes/soil4111/hw/
Available on Wayback. Yield monitor data with soils layer. 


** Jack Weiss
Ecol 563 Stat Meth in Ecology
http://www.unc.edu/courses/2010fall/ecol/563/001/
Env Studies 562 Stat for Envt Science
http://www.unc.edu/courses/2010spring/ecol/562/001/
Ecol 145
http://www.unc.edu/courses/2006spring/ecol/145/001/docs/lectures.htm


* Journals / Proceedings


** Applied Statistics in Agriculture
http://newprairiepress.org/agstatconference/
1989-2014


** Computers and Electronics in Agriculture.
http://www.sciencedirect.com/science/journal/01681699/103
Vol 1-110


** Iowa State Agricultural Research Bulletins
http://lib.dr.iastate.edu/ag_researchbulletins/

Vol 26/ 281. Cox: Analysis of Lattice and Triple Lattice.
Page 11: Lattice, 81 hybs, 4 reps
Page 24: Triple lattice, 81 hybs, 6 reps

Vol 29/347. Homeyer. Punched Card and Calculating Machine Methods for Analyzing Lattice Experiments Including Lattice Squares and the Cubic Lattice.
Page 37: Triple lattice (9 blocks * 9 hybrids) with 6 reps.
Page 60: Simple lattice, 8 blocks * 8 hybrids, 4 reps.
Page 76: Balanced lattice, 25 hybrids
Page 87: Lattice square with (k+1)/2 reps, 121 hybrids, 6 rep
Page 109: Lattice square with k+1 reps, 7 blocks * 7 hyb, 8 reps
Page 126: Cubic lattice, 16 blocks * 4 plots = 64 varieties, 9 reps, cotton

Vol 32/396. Wassom. Bromegrass Uniformity Trial: 
agridat::wassom.bromegrass.uniformity

Vol 33/424. Heady. Crop Response Surfaces and Economic Optima in Fertilizer
agridat::heady.fertilizer

Vol 34/358. Schwab. Research on Irrigation of Corn and Soybeans At Conesville.
Page 257. 2 year, 2 loc, 4 rep, 2 nitro. Stand & yield. 
Nice graph of soil moisture deficit (fig 9)

Vol. 34/463. Doll. Fertilizer Production Functions for Corn and Oats.
Table 1, 1954 Clarion Loam.  N,P,K.
Table 14, 1955 McPaul Silt Loam.  N,P.
Table 25, 1955 corn.  K,P,N.
Table 31, 1956 oats, K,P,N.  Trends difficult to establish.

Vol 34/472. Pesek. Production Surfaces and Economic Optima For Corn Yields.
Same data published in SSA journal?

Vol 34/488. Walker. Application of Game Theory Models to Decisions.

Vol 35/494. North Central Regional Potassium Studies with Alfalfa.
Page 176. Two years, several locs per state, multiple states, multiple fertilizer levels, multiple cuttings. Soil test attributes.
Page 183. Yield and %K.

Vol 35/503. North Central Regional Potassium Studies with Corn.


** Journal of Agricultural Science
http://journals.cambridge.org/action/displayJournal?jid=AGS
Vol 128(1997) - 152(2014)


** SAS Global Forum
http://support.sas.com/events/sasglobalforum/previous/online.html
22-31, 2007-2013


* Journals - Data


** Ag Data Commons
https://data.nal.usda.gov/about-ag-data-commons


** DataDryad
http://datadryad.org/


** Data In Brief
http://www.sciencedirect.com/science/journal/23523409


** Nature Scientific Data
http://www.nature.com/sdata/


** Open Data Journal for Agricultural Research
http://library.wur.nl/ojs/index.php/odjar/


* Papers


** Barrero 2013.
A multi-environment trial analysis shows slight grain yield improvement in Texas commercial maize.
http://dx.doi.org/10.1016/j.fcr.2013.04.017
Large multi-year, multi-location data here: 
http://maizeandgenetics.tamu.edu/CTP/CTP.html
Sent a note encouraging the authors to formally publish the data.


** Daillant-Spinnler 1996
Relationships between perceived sensory properties and major preference directions of 12 variaties of apples from the southern hemisphere. Food Quality and Preference, 7(2), 113-126.
Data are available in ClustVarLV package.


** Matthew A. Cleveland, John M. Hickey, Selma Forni. (2012).
A Common Dataset for Genomic Analysis of Livestock Populations.
G3, Vol 2.
http://doi.org/10.1534/g3.111.001453
The supplemental information for this paper contains data for 3534 pigs with
high-density genotypes (50000 SNPs), and a pedigree including parents and
grandparents of the animals.


** Lado 2013. 
Increased Genomic Prediction Accuracy in Wheat Breeding Through Spatial Adjustment of Field Trial Data.
GS3. http://g3journal.org/content/3/12/2105.full
Has a large haplotype data (83 MB) and two-year phenotype data with multiple traits.


** Walt Federer.
http://ecommons.library.cornell.edu/browse?type=author&value=Federer%2C+Walter+T.
Many papers by Federer. May need to browse to Federer.


** Hedrick. 1920.
Twenty years of fertilizers in an apple orchard.
https://books.google.com/books?hl=en&lr=&id=SqlJAAAAMAAJ&oi=fnd&pg=PA446
No significant differences between fertilizer treatments--maybe a more
powerful analysis could find one?


** Kenward, Michael G. (1987).  
A Method for Comparing Profiles of Repeated Measurements.  
Applied Statistics, 36, 296-308.
An ante-dependence model is fit to repeated measures of cattle weight.
Data available here:
https://faculty.biostat.ucla.edu/robweiss/filedepot_download/87/495


** Klumper & Qaim 2015. 
A Meta-Analysis of the Impacts of Genetically Modified Crops
http://dx.doi.org/10.1371/journal.pone.0111629
Nice meta-analysis dataset.  Published data only include differences, not standard-errors.


** Roger Payne (2015). 
The Design and Analysis of Long-Term Rotation Experiments.
Agronomy Journal, 107, 772-784.
http://doi.org/10.2134/agronj2012.0411
The data and R code appeared in the paper. Free access, but closed copyright.


** Technow et al 2014.
Genome Properties and Prospects of Genomic Prediction of Hybrid Performance in a Breeding Program of Maize.
http://doi.org/10.1534/genetics.114.165860
Genotype and phenotype data appears in the sommer package.


** Ting Tian 2015.
Application of Multiple Imputation for Missing Values in Three-Way Three-Mode Multi-Environment Trial Data.
http://doi.org/10.1371/journal.pone.0144370
Uses australia.soybean data and one other real dataset with 4 traits that are not identified.  All data and code available.


** Wisser 2011. 
Multivariate analysis of maize disease resistances suggests a pleiotropic
genetic basis and implicates a GST gene. PNAS.
http://doi.org/10.1073/pnas.1011739108
Supplement contains genotype data, but no phenotype data.


** Yan 2002.  
Singular value partitioning in biplots.
Agron Journal.
Winter wheat, 31 gen in 8 loc. This data is different from Yan's earlier papers.


* Papers - Uniformity trials


** Baker 1953. 
Strawberry uniformity yield trials. Biometrics,
Vol. 9, No. 3 (Sep., 1953), pp. 412-421.
http://doi.org/10.2307/3001713
Two uniformity trials with yield per plant for 200, 500 plants.  CVs fairly
high and correlation between neighboring plants very low.


** R D Bose, 1935.
Some soil-heterogeneity trials at Pusa and the size and shape of experimental
plots. Indian Jour. Agr. Sci. 5 (5), 579-608.
This paper is not available, but a summary can be found here:
http://digital.library.unt.edu/ark:/67531/metadc5082/m1/496/


** Moore, John Francis, 1952.
A study of field plot technique with sprouting broccoli. 
Proc Amer Soc Hort Sci: 1-474.
This paper is not available, but a summary can be found here:
http://eurekamag.com/research/013/624/013624967.php


* R packages


** agricolae 
Has assorted data and functions for analysis.


** BGLR Bayesian Generalized Linear Regression.
Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.


** BLR Bayesian Linear Regression.
Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.


** BSagri
Safety assessment in agriculture trials

** ClustVarLV
The apples_sh data has sensory attributes and preference scores for 12 apple varieties.


** cropcc Climate change on crops
https://r-forge.r-project.org/projects/cropcc/


** drc
Has nice herbicide dose response curves and germination data for
mungbean, rice, wheat.


** FW Finlay-Wilkinson regression
https://github.com/lian0090/FW/ 
Has phenotype data and marker data for 599 wheat lines in 4 environments.


** lmtest::ChickEgg 
Time series of annual chicken and egg production in the United States 1930-1983.


** lsmeans 
Data: feedlot.
Used to demonstrate an unbalanced analysis-of-covariance.


** missMDA 
The referenced source for 'geno' data does NOT contain the data.


** nlraa Non-linear models in agriculture.
http://r-forge.r-project.org/R/?group_id=1599
Miguez.  R package: Non-linear models in agriculture.  Not a meta-analysis.

   
** nlme
Datasets for growth of Orange trees and Soybean plants.
Soybean data is from "Nonlinear Models for Repeated Measurement Data".


** plantbreeding  
https://r-forge.r-project.org/projects/plantbreeding/
Data: fulldial
Data: linetester
Data: peanut: agridat::kang.peanut


** SDaA Survey Data and Analysis
This package has county-level data from the United States Census of
Agriculture, along with a vignette to illustrate survey sampling analyses.


** SemiPar
Data: onions: agridat::ratkowski.onions


** sommer Solving mixed model equations in R
Data: h2. Modest-sized GxE experiment in potato
Data: cornHybrid. Yield/PLTHT for 100 hybrids from 20 inbred * 20 inbred, 4 locs. Phenotype and relationship matrix.
Data: wheatLines  CIMMYT wheat data for 599 lines. Phenotype and relationship data.
Data: RICE
Data: FDdata taken from agridat::bond.diallel
Data: Technow_data. AF=Additive Flint. AD=Additive Dent. MF=Marker Flint. MD=Marker Dent. pheno=phenotype data for 1254 hybrids (GY=yield, GM=moisture).  This data is from Technow et al:
http://www.genetics.org/content/197/4/1343.supplemental


** spdep 
Has a vignette 'The Problem of Spatial Autocorrelation: forty years
on' that examines agriculture in Irish counties.
See also the data ade4::irishdata. 


** SoyNAM Soybean nested association mapping 
Dataset with phenotype data 3 yr,
9 locations, 18 environments, 60 thousand observations for height, maturity,
lodging, moisture, protein, oil, fiber, seed size. There are 5000+ strains,
40 families.

** st4gi Stat for genetic improvement
https://github.com/reyzaguirre/st4gi


* Web sites


** ARS oat trials
http://www.ars.usda.gov/Main/docs.htm?docid=8419&page=4


** Electronic Rothamsted Archive
http://www.era.rothamsted.ac.uk/index.php
Data from Broadbalk and other long-term experiments.


** Electronic Rothamsted Documents Archive
http://www.era.rothamsted.ac.uk/eradoc/collections.php
Annual reports from Rothamsted 1908-1987. Many have data.


** Germplasm Enhancement of Maize (ISU)
http://www.public.iastate.edu/~usda-gem/index.htm
Data from trials at multiple locations. Yield, mst, pltht, lodging. No field plans.


** Google datasets search engine
https://cse.google.com/cse/publicurl?cx=002720237717066476899:v2wv26idk7m


** Illinois Corn Hybrid Variety Trials
http://vt.cropsci.illinois.edu/corn.html


** ILRI International Livestock Research Institute
http://www.ilri.org/biometrics/CS/
Case study 4 is a nice dialel example with sheep data.  agridat::ilri.sheep


** IRRI Biometrics and Breeding Informatics
http://bbi.irri.org/products
STAR, PBTools, CropStat.
The STAR user guide has well-documented data (even using 2 from agridat), but
the PBTools user guide does not document the data.


** USDA National Agricultural Statistics Service
http://www.nass.usda.gov
http://quickstats.nass.usda.gov/
Group:       Field Crops
Commodity:   Corn
Category:    Area Harvested, Yield
Data Item:   Corn grain Acres Harvested, Yield Bu/Ac
Domain:      Total
Geography:   State
See agridat::nass.corn, nass.wheat, etc.
