# agridat notes

This document lists notes about data sources searched and additional sources of agricultural data.  Although this is an .Rmd file, the formatting is best viewed in plain text mode.

---

Hansen 1914 Aarslov Tidsskrift for landbrugets planteavl
http://dca.au.dk/publikationer/historiske/planteavl/ Bind 21 has 1914, page 553.

Eden & Maskell say":
One of the trials, comprising 35 plots, extended over the years 1907-11 and included oats, rye, barley, roots, barley.
Hansen's analysis:
Oats and rye 1907 and 1908 show marked positive correlation
rye and barley 1908 and 1909 no correlation of significance
barley and roots 1909 and 1910 no correlation
roots and barley 1910 and 1911 a significant correlation
rye and roots 1908 and 1910 satisfactory

---
Two trials, modest size, page 230
https://archive.org/stream/in.ernet.dli.2015.25282/2015.25282.The-Empire-Journal-Of-Experimental-Agriculture-Vol-v-1937#page/n235/mode/2up/search/uniformity
---

https://babel.hathitrust.org/cgi/pt?id=wu.89031116783;view=1up;seq=3
https://babel.hathitrust.org/cgi/pt?id=uc1.$b34460;view=1up;seq=14

---
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0157166

---
Iowa State Univ Library Special Collections

Field plot techniques for sweet potatoes obtained from uniformity trial data
Helen Elizabeth Conners. 1951
C O 1951 Conners

Field plot techniques for estimating onion yields 
Robert LeRoy Plaisted. 1954 
C O 1954 Plaisted

Plot technique for field evaluation of three characters in the lima bean
Michael Holle. 1960
C O 1960 Holle

---
Henry Wallace archive at Univ Iowa Library
http://www.lib.uiowa.edu/sc/location-and-hours/
Henry Wallace research papers
http://aspace.lib.uiowa.edu/repositories/2/archival_objects/400608
500 Ear experiment. Might be the data for "What is in the corn judge's mind" paper
http://aspace.lib.uiowa.edu/repositories/2/archival_objects/400615
---

rpathanalysis
http://cucurbitbreeding.com/todd-wehner/publications/software-sas-r-project/

# wanted

Plant-level data for distinctness, uniformity and stability testing.  Most published data is for plot-means.
This page mentions an R version for DUS: http://www.bioss.ac.uk/knowledge/software.html



# stability


# done
adugna.sorghum 28g,13l,5y
brandle.rape 5g,9l,3y
denis.missing 5g,26e
digby.jointregression 10g,17l
fan.stability 13g,10l,2y
hildebrand.systems
huehn.wheat 20g,10e 
lu.stability 5g,6e
pieopho.cocksfoot 25g,7y
williams.trees 37g,6l

# todo ?
kamidi 11g,7l 
lin.balanced 33g,12l 
lin.unbalanced 33g,18l

Oakey, Cullis, Thompson http://www.g3journal.org/content/6/5/1313/suppl/DC1

---

## Rothamsted Annual Reports  
http://www.era.rothamsted.ac.uk/eradoc/books/1
Most of the annual reports have a section on Classical Experiments.
'''
Year,page
1908-1926 
1926-1927 agridat::sawyer.multi.uniformity 
1927-1928 agridat::sawyer.multi.uniformity
1929-1930
1931,143 agridat::yates.oats
1932
1933
1934,215-222 Sugar beet multi-environment trial with 3^3 fertilizer treatments at each site Roots, SugarPercent, SugarWeight, PlantNumber, Tops, Purity.
1935
1936,241 Similar to the 1934 experiment, but only gives the main effects, not the actual data.
1937
1938
1939
1946 few results
1947
1948
1949
1950
1951 1952 1953
'''
---


Jose Crossa papers http://repository.cimmyt.org/xmlui/handle/10883/1/browse?value=Crossa,%20J.&type=author 
Meta-r http://repository.cimmyt.org/xmlui/handle/10883/4130 
Data http://repository.cimmyt.org/xmlui/handle/10883/4036 
http://repository.cimmyt.org/xmlui/handle/10883/2976 
http://repository.cimmyt.org/xmlui/handle/10883/1380 
http://repository.cimmyt.org/xmlui/handle/10883/4128 http://repository.cimmyt.org/xmlui/handle/10883/4290


Die Landwirtschaftlichen Versuchs-Stations http://catalog.hathitrust.org/Record/000549685

Summary of meta-analyses http://www6.versailles-grignon.inra.fr/agronomie/Meta-analysis-in-agronomy/References

QTL analysis using Integrated Breeding Platform.  https://www.integratedbreeding.net/165/training/bms-user-manual/qtl-analysis CC-BY-SA license

Richard Plant http://www.plantsciences.ucdavis.edu/plant/qgislabs.htm CC-SA license

MapCalc http://www.innovativegis.com/basis/ Joseph Berry.  Looks interesting, free for education.  Center pivot data.

Analyzing Precision Ag Data <-- interesting workshop 
http://www.innovativegis.com/basis/Books/AnalyzingPAdata/Default.htm http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Support_materials/Default.htm http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Default.htm

http://www.innovativegis.com/basis/pfprimer/Appendix_D/Appendix_D.htm http://www.innovativegis.com/basis/pfprimer/Topic4/Topic4.htm

# Papers

Biplot/StdErr/
VanEeuwijk 1993 - Incorporating env info Biplot
Bartkowiak GxE table GE folder: Crossa 1997

Stability folder 
Fan 2007 - Yield stability of maize GxE 
Flores 1998 Flores 1998 - bean & pea yields, Flores 2012, Flores 2013

Jode Edwards Data analyzed in this report were obtained from the Iowa State University Oat Variety Trial for the years 1997 to 2003.


## Malosetti 2013
F2 data.  
Folder: GE http://www.frontiersin.org/Plant_Physiology/10.3389/fphys.2013.00044/abstract CC license:


## da Silva
A Bayesian Shrinkage Approach for AMMI Models http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0131414#pone-0131414-t001 CC-BY. Partial code, data.


## Perez
Comparison Between Linear and Non-parametric Regression Models for Genome-Enabled Prediction in Wheat https://www.scienceopen.com/document/vid/4017fb51-381c-4374-93aa-608423df4004;jsessionid=0TLjjSbaooSUk1y3JKd4nUeb.master:so-app1-prd Data: http://www.g3journal.org/content/suppl/2012/12/05/2.12.1595.DC1 All content has CC license


# Other
Many interesting pages.  Non-open license...?  Lecture and data http://articles.extension.org/plant_breeding_genomics http://articles.extension.org/pages/68660/plant-breeding-and-genomics-learning-lessons http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar http://articles.extension.org/pages/61006/estimating-heritability-and-blups-for-traits-using-tomato-phenotypic-data <--- http://articles.extension.org/pages/68019/genomic-relationships-and-gblup http://pbgworks.org/node/1440


Jennifer Kling Lattice Design.  Data at bottom.
 http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar http://cropandsoil.oregonstate.edu/system/files/u534/Lattice_seminar.pdf https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447275 https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447276 https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447273



# Journals

## Agronomy Journal
Skimmed Vol 1

## Biometrics. Skimmed 1947-2006
http://www.jstor.org/action/showPublication?journalCode=biometrics

## Field Crops Research. 
http://www.sciencedirect.com/science/journal/03784290/157 Vol 1-40

## IASRI newsletters
http://www.iasri.res.in/NewsLetters/nl.HTM

## JABES
Vol 6.

## Journal of the Indian Society of Agricultural Statistics
http://www.isas.org.in/jsp/onlinejournal.jsp Skimmed: Vol 50-56

## JRSSA

## JRSSB 1940-1997
http://www.jstor.org/action/showPublication?journalCode=jroyastatsocise4 Datasets 1998-2015 http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9868/homepage/seriesb_datasets.htm http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm

## JRSSC Applied Statistics datasets
http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm 1998-2015

## The American Statistician
Vol 1-13

# ----------------------------------------------------------------------------

# Books

## Maize International Testing 1982. CIMMYT.
http://pdf.usaid.gov/pdf_docs/PNAAQ389.pdf

## Annual report - Nebraska Agricultural Experiment Station
Vol 19-24, 1906-1911 https://books.google.com/books?id=HBlJAAAAMAAJ


# Classes


## Hernandez
http://www.soils.umn.edu/academics/classes/soil4111/hw/ Available on Wayback. Yield monitor data with soils layer.


## Jack Weiss
Ecol 563 Stat Meth in Ecology 
http://www.unc.edu/courses/2010fall/ecol/563/001/ 
Env Studies 562 Stat for Envt Science 
http://www.unc.edu/courses/2010spring/ecol/562/001/ 
Ecol 145 
http://www.unc.edu/courses/2006spring/ecol/145/001/docs/lectures.htm


# Journals / Proceedings


## Applied Statistics in Agriculture
http://newprairiepress.org/agstatconference/ 1989-2014


## Computers and Electronics in Agriculture.
http://www.sciencedirect.com/science/journal/01681699/103 Vol 1-110



## Journal of Agricultural Science
https://www.cambridge.org/core/journals/journal-of-agricultural-science/all-issues
1900-2016

## Experimental Agriculture
https://www.cambridge.org/core/journals/experimental-agriculture
1965-2016

## SAS Global Forum
http://support.sas.com/events/sasglobalforum/previous/online.html 22-31, 2007-2013


