#+title: agridat notes

This document lists notes about data sources searched and additional sources of agricultural data.  Although this is an .org file, the formatting is best viewed in plain text mode.

---
Henry Wallace archive at Univ Iowa Library
http://www.lib.uiowa.edu/sc/location-and-hours/
Henry Wallace research papers
http://aspace.lib.uiowa.edu/repositories/2/archival_objects/400608
500 Ear experiment. Might be the data for "What is in the corn judge's mind" paper
http://aspace.lib.uiowa.edu/repositories/2/archival_objects/400615
---

rpathanalysis
http://cucurbitbreeding.com/todd-wehner/publications/software-sas-r-project/

* wanted

Plant-level data for distinctness, uniformity and stability testing.  Most published data is for plot-means.
This page mentions an R version for DUS: http://www.bioss.ac.uk/knowledge/software.html



* stability


* done
adugna.sorghum 28g,13l,5y
brandle.rape 5g,9l,3y
denis.missing 5g,26e
digby.jointregression 10g,17l
fan.stability 13g,10l,2y
hildebrand.systems
huehn.wheat 20g,10e 
lu.stability 5g,6e
pieopho.cocksfoot 25g,7y
williams.trees 37g,6l

* todo ?
kamidi 11g,7l 
lin.balanced 33g,12l 
lin.unbalanced 33g,18l

Oakey, Cullis, Thompson http://www.g3journal.org/content/6/5/1313/suppl/DC1


** Rothamsted Annual Reports  
http://www.era.rothamsted.ac.uk/eradoc/books/1
Most of the annual reports have a section on Classical Experiments, often featuring RCB or Latin Square experiments.
Done: 
1908-1926 
1926-1927. agridat::sawyer.multi.uniformity 
1927-1928. agridat::sawyer.multi.uniformity
1929
---


Jose Crossa papers http://repository.cimmyt.org/xmlui/handle/10883/1/browse?value=Crossa,%20J.&type=author 
Meta-r http://repository.cimmyt.org/xmlui/handle/10883/4130 
Data http://repository.cimmyt.org/xmlui/handle/10883/4036 
http://repository.cimmyt.org/xmlui/handle/10883/2976 
http://repository.cimmyt.org/xmlui/handle/10883/1380 
http://repository.cimmyt.org/xmlui/handle/10883/4128 http://repository.cimmyt.org/xmlui/handle/10883/4290


Die Landwirtschaftlichen Versuchs-Stations http://catalog.hathitrust.org/Record/000549685

Summary of meta-analyses http://www6.versailles-grignon.inra.fr/agronomie/Meta-analysis-in-agronomy/References

QTL analysis using Integrated Breeding Platform.  https://www.integratedbreeding.net/165/training/bms-user-manual/qtl-analysis CC-BY-SA license

Richard Plant http://www.plantsciences.ucdavis.edu/plant/qgislabs.htm CC-SA license

MapCalc http://www.innovativegis.com/basis/ Joseph Berry.  Looks interesting, free for education.  Center pivot data.

Analyzing Precision Ag Data <-- interesting workshop 
http://www.innovativegis.com/basis/Books/AnalyzingPAdata/Default.htm http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Support_materials/Default.htm http://www.innovativegis.com/basis/Books/AnalyzingPAdata/PA_download/Default.htm

http://www.innovativegis.com/basis/pfprimer/Appendix_D/Appendix_D.htm http://www.innovativegis.com/basis/pfprimer/Topic4/Topic4.htm

* Papers

Biplot/StdErr/VanEeuwijk 1993 - Incorporating env info Biplot/Bartkowiak GxE table GE folder: Crossa 1997

Stability folder Fan 2007 - Yield stability of maize GxE / Flores 1998 Flores 1998 - bean & pea yields, Flores 2012, Flores 2013

Jode Edwards Data analyzed in this report were obtained from the Iowa State University Oat Variety Trial for the years 1997 to 2003.


** Malosetti 2013
F2 data.  
Folder: GE http://www.frontiersin.org/Plant_Physiology/10.3389/fphys.2013.00044/abstract CC license:


** da Silva
A Bayesian Shrinkage Approach for AMMI Models http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0131414#pone-0131414-t001 CC-BY. Partial code, data.


** Perez
Comparison Between Linear and Non-parametric Regression Models for Genome-Enabled Prediction in Wheat https://www.scienceopen.com/document/vid/4017fb51-381c-4374-93aa-608423df4004;jsessionid=0TLjjSbaooSUk1y3JKd4nUeb.master:so-app1-prd Data: http://www.g3journal.org/content/suppl/2012/12/05/2.12.1595.DC1 All content has CC license

** VanEeuwijk 1998.
van Eeuwijk, Fred A. and Pieter M. Kroonenberg (1998).
Multiplicative Models for Interaction in Three-Way ANOVA, with Applications to Plant Breeding
Biometrics, 54, 1315-1333. http://doi.org/10.2307/2533660


* Other
Many interesting pages.  Non-open license...?  Lecture and data http://articles.extension.org/plant_breeding_genomics http://articles.extension.org/pages/68660/plant-breeding-and-genomics-learning-lessons http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar http://articles.extension.org/pages/61006/estimating-heritability-and-blups-for-traits-using-tomato-phenotypic-data <--- http://articles.extension.org/pages/68019/genomic-relationships-and-gblup http://pbgworks.org/node/1440


Jennifer Kling Lattice Design.  Data at bottom.
 http://articles.extension.org/pages/60430/introduction-to-the-augmented-experimental-design-webinar http://cropandsoil.oregonstate.edu/system/files/u534/Lattice_seminar.pdf https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447275 https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447276 https://passel.unl.edu/pages/informationmodule.php?idinformationmodule=1130447273



* Journals

** Agronomy Journal
Skimmed Vol 1

** Biometrics. Skimmed 1947-2006
http://www.jstor.org/action/showPublication?journalCode=biometrics

** Field Crops Research. 
http://www.sciencedirect.com/science/journal/03784290/157 Vol 1-40

** IASRI newsletters
http://www.iasri.res.in/NewsLetters/nl.HTM

** JABES
Vol 6.

** Journal of the Indian Society of Agricultural Statistics
http://www.isas.org.in/jsp/onlinejournal.jsp Skimmed: Vol 50-56

** JRSSA

** JRSSB 1940-1997
http://www.jstor.org/action/showPublication?journalCode=jroyastatsocise4 Datasets 1998-2015 http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9868/homepage/seriesb_datasets.htm http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm

** JRSSC Applied Statistics datasets
http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291467-985X/homepage/datasets_all_series.htm 1998-2015

** The American Statistician
Vol 1-13

* ----------------------------------------------------------------------------

* Books

** Maize International Testing 1982. CIMMYT.
http://pdf.usaid.gov/pdf_docs/PNAAQ389.pdf

** Annual report - Nebraska Agricultural Experiment Station
Vol 19-24, 1906-1911 https://books.google.com/books?id=HBlJAAAAMAAJ

** Paterson. 1939. Statistical Technique In Agricultural Research.
http://www.archive.org/details/statisticaltechn031729mbp



* Classes



** Hernandez
http://www.soils.umn.edu/academics/classes/soil4111/hw/ Available on Wayback. Yield monitor data with soils layer.


** Jack Weiss
Ecol 563 Stat Meth in Ecology 
http://www.unc.edu/courses/2010fall/ecol/563/001/ 
Env Studies 562 Stat for Envt Science 
http://www.unc.edu/courses/2010spring/ecol/562/001/ 
Ecol 145 
http://www.unc.edu/courses/2006spring/ecol/145/001/docs/lectures.htm


* Journals / Proceedings


** Applied Statistics in Agriculture
http://newprairiepress.org/agstatconference/ 1989-2014


** Computers and Electronics in Agriculture.
http://www.sciencedirect.com/science/journal/01681699/103 Vol 1-110


** Iowa State Agricultural Research Bulletins
http://lib.dr.iastate.edu/ag_researchbulletins/

Vol 26/ 281. Cox: Analysis of Lattice and Triple Lattice.  
Page 11: Lattice, 81 hybs, 4 reps 
Page 24: Triple lattice, 81 hybs, 6 reps

Vol 29/347. Homeyer. Punched Card and Calculating Machine Methods for Analyzing Lattice Experiments Including Lattice Squares and the Cubic Lattice.  
Page 37: Triple lattice (9 blocks * 9 hybrids) with 6 reps.  
Page 60: Simple lattice, 8 blocks * 8 hybrids, 4 reps.  
Page 76: Balanced lattice, 25 hybrids 
Page 87: Lattice square with (k+1)/2 reps, 121 hybrids, 6 rep 
Page 109: Lattice square with k+1 reps, 7 blocks * 7 hyb, 8 reps 
Page 126: Cubic lattice, 16 blocks * 4 plots = 64 varieties, 9 reps, cotton

Vol 32/396. Wassom. Bromegrass Uniformity Trial: agridat::wassom.bromegrass.uniformity

Vol 33/424. Heady. Crop Response Surfaces and Economic Optima in Fertilizer agridat::heady.fertilizer

Vol 34/358. Schwab. Research on Irrigation of Corn and Soybeans At Conesville.  
Page 257. 2 year, 2 loc, 4 rep, 2 nitro. Stand & yield.  Nice graph of soil moisture deficit (fig 9)

Vol. 34/463. Doll. Fertilizer Production Functions for Corn and Oats.  
Table 1, 1954 Clarion Loam.  N,P,K.  
Table 14, 1955 McPaul Silt Loam.  N,P.  
Table 25, 1955 corn.  K,P,N.  
Table 31, 1956 oats, K,P,N.  Trends difficult to establish.

Vol 34/472. Pesek. Production Surfaces and Economic Optima For Corn Yields.  Same data published in SSA journal?

Vol 34/488. Walker. Application of Game Theory Models to Decisions.

Vol 35/494. North Central Regional Potassium Studies with Alfalfa.  
Page 176. Two years, several locs per state, multiple states, multiple fertilizer levels, multiple cuttings. Soil test attributes.  
Page 183. Yield and %K.

Vol 35/503. North Central Regional Potassium Studies with Corn.


** Journal of Agricultural Science
https://www.cambridge.org/core/journals/journal-of-agricultural-science/all-issues
1900-2016

** Experimental Agriculture
https://www.cambridge.org/core/journals/experimental-agriculture
1965-2016

** SAS Global Forum
http://support.sas.com/events/sasglobalforum/previous/online.html 22-31, 2007-2013


