---
title: "Additional sources of agricultural data"
author: "Kevin Wright"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional sources of agricultural data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<style type="text/css">
body, td { font-size: 14pt; color: #000; padding:1em; }
code, pre, #ws, #message { font-size: 12pt;
  color: #000; background-color: #f5f5f5; }
code {border: 1px solid #e0e0e0; padding: 0 5px;}
pre > code { border: 0; }
</style>

## Abstract

This document lists additional sources of agricultural data.

## Books

D. Bayisa (2010). _Application of Spatial Mixed Model in Agricultural Field
Experiment_. Master thesis. Department of Statistics, Addis Ababa University.
At least one dataset from wheat, RCB, with field coordinates.
See also http://www.ethstat.org.et/esa_publications.html, Volume 19

Peter Diggle. _Longitudinal Data Analysis_.
http://www.maths.lancs.ac.uk/~diggle/lda/Datasets/

The Pig weight data is in the package `SemiPar::pig.weights`.

The Sitka spruce data is in `geepack::spruce`.

The Milk protein data is in `nlme::Milk`.

Cyril H. Goulden, _Methods of Statistical Analysis_. Second edition.
First edition: http://archive.org/details/methodsofstatist031744mbp
18 Uniformity trial. `agridat::goulden.barley.uniformity`
153 Split-split plot with factorial sub-plot treatment <-- todo
194 Incomplete block
197 Inc block
205 Latin square
208 Inc block

Second edition: http://krishikosh.egranth.ac.in/handle/1/2034118
216 Latin square. `agridat::goulden.latin`
423 Control chart with egg weights. `agridat::goulden.eggs`

## Papers

Baker 1953. Strawberry uniformity yield trials. _Biometrics_,
Vol. 9, No. 3 (Sep., 1953), pp. 412-421.
http://doi.org/10.2307/3001713
Two uniformity trials with yield per plant for 200, 500 plants.  CVs fairly
high and correlation between neighboring plants very low.

Kenward, Michael G. (1987).  A Method for Comparing Profiles of Repeated
Measurements.  _Applied Statistics_, 36, 296-308.
An ante-dependence model is fit to repeated measures of cattle weight.
Data available here:
https://faculty.biostat.ucla.edu/robweiss/filedepot_download/87/495

Roger Payne (2015). The Design and Analysis of Long-Term Rotation Experiments.
_Agronomy Journal_, 107, 772-784.
https://www.agronomy.org/publications/aj/pdfs/107/2/772
Contains data and R code.

Matthew A. Cleveland, John M. Hickey, Selma Forni. (2012).
A Common Dataset for Genomic Analysis of Livestock Populations
_G3_, Vol 2.
http://doi.org/10.1534/g3.111.001453
The supplemental information for this paper contains data for 3534 pigs with
high-density genotypes (50000 SNPs), and a pedigree including parents and
grandparents of the animals.

1982 CIMMYT trials.
http://pdf.usaid.gov/pdf_docs/PNAAQ389.pdf

## R packages

`agricolae` has assorted data and functions for analysis.

`BGLR`. Bayesian Generalized Linear Regression.
Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.

`BLR`. Bayesian Linear Regression.
Has an A matrix (but no pedigree) for 499 genotypes at 4 locations.

`cropcc`. Climate change on crops.
https://r-forge.r-project.org/projects/cropcc/

`drc` is a package for dose response curves, including germination data for
mungbean, rice, wheat.

`FW` https://github.com/lian0090/FW/ has phenotype data and marker data for
599 wheat lines in 4 environments.

`lmtest::ChickEgg` has time series of annual chicken and egg
production in the United States 1930-1983.

`lsmeans::feedlot` is used to demonstrate an unbalanced
analysis-of-covariance.

`nlraa` is for Non-linear models in agriculture.
http://r-forge.r-project.org/R/?group_id=1599

`nlme::Orange` shows growth of orange trees.

`plantbreeding`
https://r-forge.r-project.org/projects/plantbreeding/

`SDaA` This package has county-level data from the United States Census of
Agriculture, along with a vignette to illustrate survey sampling analyses.
http://cran.r-project.org/package=SDaA

`spdep` has a vignette 'The Problem of Spatial Autocorrelation: forty years
on' that examines agriculture in Irish counties.  See also the data
`ade4::irishdata`. 

`SoyNAM` Soybean nested association mapping dataset with phenotype data 3 yr,
9 locations, 18 environments, 60 thousand observations for height, maturity,
lodging, moisture, protein, oil, fiber, seed size. There are 5000+ strains,
40 families.


## Web sites

Electronic Rothamsted Archive
http://www.era.rothamsted.ac.uk/index.php

Electronic Rothamsted Documents Archive
http://www.era.rothamsted.ac.uk/eradoc/collections.php

Statistical Analysis of Agricultural Experiments with R
http://rstats4ag.org/
