---
title: "Notes on uniformity data"
author: "Kevin Wright"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Notes on uniformity data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Todo

To do: Figure out appendix II.
Mathew, Lucyamma. Standardization of field plot technique for cashew. Diss. Department of Statistics, College of Veterinary and Animal Sciences, Mannuthy.
https://krishikosh.egranth.ac.in/handle/1/5810142095


Contact Rothamsted to scan uniformity trial papers.


# Added to agridat

Ansari, M. A. A., and G. K. Sant (1943).
A Study of Soil Heterogeneity in Relation to Size and Shape of Plots in a Wheat Field at Raya (Muhra District).
Ind. J. Agr. Sci, 13, 652-658.
https://archive.org/details/in.ernet.dli.2015.271748

Baker, GA and Huberty, MR and Veihmeyer, FJ.  (1952)
A uniformity trial on unirrigated barley of ten years' duration.
Agronomy Journal, 44, 267-270.
http://doi.org/10.2134/agronj1952.00021962004400050011x

Baker, G. A.; and R. E. Baker (1953).
Strawberry Uniformity Yield Trials.
Biometrics, 9, 412-421.
http://doi.org/10.2307/3001713

G. A. Baker, E. B. Roessler (1957).
Implications of a uniformity trial with small plots of wheat.
Hilgardia, 27, 183-188.
http://hilgardia.ucanr.edu/Abstract/?a=hilg.v27n05p183

Bancroft, T. A. et a1., (1948).
Size and Shape of Plots and Distribution of Plot Yield for Field Experiments with Peanuts.
Alabama Agricultural Experiment Station Progress Report, sec. 39.
Table 4, page 6.
https://aurora.auburn.edu/bitstream/handle/11200/1345/0477PROG.pdf;sequence=1

Batchelor, L. D.; and H. S. Reed. (1918).
Relation of the variability of yields of fruit trees to the accuracy of field trials. 
J. Agric. Res, 12, 245--283.
http://books.google.com/books?id=Lil6AAAAMAAJ&lr&pg=PA245

Bose, R. D. (1935).
Some soil heterogeneity trials at Pusa and the size and shape of experimental plots. 
Ind. J. Agric. Sci., 5, 579-608. Table 1 (p. 585), Table 4 (p. 589), Table 5 (p. 590).
https://archive.org/details/in.ernet.dli.2015.271739

Bradley, P. L. (1941).
A study of the variation in productivity over a number of fixed plots in field 2.
Dissertation: The University of the West Indies. Appendix 1a, 1b, 1c, 1d.
http://hdl.handle.net/2139/41264

The data are repeated in:
C. E. Wilson.
Study of the plots laid out on field II with a view to obtaining
plot-fertility data for use in future experiments on these plots,
season 1940-41.
Dissertation: The University of the West Indies.  Page 36-39.
http://uwispace.sta.uwi.edu/dspace/handle/2139/43658

Christidis, B. G. (1939).
Variability of Plots of Various Shapes as Affected by Plot Orientation.
Empire Journal of Experimental Agriculture 7: 330-342. Table 1.

Christidis, Basil G (1931).
The importance of the shape of plots in field experimentation.
The Journal of Agricultural Science, 21, 14-37. Table VI, p. 28.
http://dx.doi.org/10.1017/S0021859600007942

da Silva, Enedino Correa. (1974).
Estudo do tamanho e forma de parcelas para experimentos de soja (Plot size and shape for soybean yield trials).
Pesquisa Agropecuaria Brasileira, Serie Agronomia, 9, 49-59. Table 3,
page 52-53.
http://seer.sct.embrapa.br/index.php/pab/article/view/17250

Davies, J. Griffiths (1931).
The Experimental Error of the Yield from Small Plots of Natural Pasture.
Council for Scientific and Industrial Research (Aust.) Bulletin 48.
Table 1.

Day, James Westbay (1916).
The relation of size, shape, and number of replications of plats to probable error in field experimentation.
Dissertation, University of Missouri. Table 1, page 22.
https://hdl.handle.net/10355/56391

Draper, Arlen D. (1959).
Optimum plot size and shape for safflower yield tests.
Dissertation. University of Arizona. 
http://hdl.handle.net/10150/319371

Edan, T. (1931).
Studies in the yield of tea. 1. The experimental errors of field experiments with tea.
Agricultural Science, 21, 547-573.
https://doi.org/10.1017/S0021859600088511

Garber, RJ and Mcllvaine, TC and Hoover, MM. 1926.
A study of soil heterogeneity in experiment plots.
Jour Agr Res, 33, 255-268. Tables 3, 5.
http://naldc.nal.usda.gov/download/IND43967148/PDF

Gomez, K.A. and Gomez, A.A. (1984).
Statistical Procedures for Agricultural Research.
Wiley-Interscience. Page 481.

Goulden, C. H. (1939).
Methods of statistical analysis, 1st ed. Page 18.
https://archive.org/stream/methodsofstatist031744mbp

Harris, J Arthur and Scofield, CS. (1920).
Permanence of differences in the plats of an experimental field.
Jour. Agr. Res., 20, 335-356.
http://naldc.nal.usda.gov/catalog/IND43966236

Harris, J. Arthur and Scofield, CS. (1928).
Further studies on the permanence of differences in the plots of an experimental field.
Jour. Agr. Res. 36, 15--40.
http://naldc.nal.usda.gov/catalog/IND43967538

Harris, J.A. 1920. 
Practical universality of field heterogeneity as a factor influencing plot yields.
Journal of Agricultural Research, 19, 279--314. Page 296-297.
http://books.google.com/books?id=jyEXAAAAYAAJ&pg=PA279

Hartman, J. D.; and E. C. Stair (1942).
Proceedings Of The American Society For Horticultural Science, 41, 315-320.
https://archive.org/details/in.ernet.dli.2015.240678

Heath, O.V.S. (1970).
Investigation by Experiment. Table 1.
https://archive.org/details/investigationbye0000heat

Holtsmark, G and Larsen, BR (1905).
Om Muligheder for at indskraenke de Fejl, som ved Markforsog betinges af Jordens Uensartethed.
Tidsskrift for Landbrugets Planteavl. 12, 330-351. (In Danish)
https://books.google.com/books?id=MdM0AQAAMAAJ&pg=PA330
http://dca.au.dk/publikationer/historiske/planteavl/

Igue, Toshio; Ademar Espironelo, Heitor Cantarella, Erseni Joao Nelli. (1991).
Tamanho e forma de parcela experimental para cana-de-acucar (Plot size and shape for sugar cane experiments).
Bragantia, 50, 163-180. Appendix, page 169-170.
http://dx.doi.org/10.1590/S0006-87051991000100016

Immer, F. R. (1932).
Size and shape of plot in relation to field experiments with sugar beets.
Jour. Agr. Research, 44, 649--668.
http://naldc.nal.usda.gov/download/IND43968078/PDF

Jones, Marcus; Marin Harbur, and Ken J. Moore (2021).
Automating Uniformity Trials to Optimize Precision of Agronomic Field Trials.
Agronomy 2021, 11, 1254.
https://doi.org/10.3390/agronomy11061254
Data from 12x12 corn expt.

Iyer, P. V. Krishna (1942).
Studies with wheat uniformity trial data. I. Size and shape of experimental plots and the relative efficiency of different layouts.
The Indian Journal of Agricultural Science, 12, 240-262. Page 259-262.
https://archive.org/stream/in.ernet.dli.2015.7638/2015.7638.The-Indian-Journal-Of-Agricultural-Science-Vol-xii-1942#page/n267/mode/2up

Kadam, B. S. Kadam; and S. M. Patel. (1937).
Studies in Field-Plot Technique With P. Typhoideum Rich.
The Empire Journal Of Experimental Agriculture, 5, 219-230.
https://archive.org/details/in.ernet.dli.2015.25282

Kalamkar, R.J. (1932).
Experimental Error and the Field-Plot Technique with Potatoes.
The Journal of Agricultural Science, 22, 373-385.
http://doi.org/10.1017/S0021859600053697

Kalamkar, R. J (1932).
A Study in Sampling Technique with Wheat.
The Journal of Agricultural Science, Vol.22(4), pp.783-796.
https://doi.org/10.1017/S0021859600054599

Kempton, R. A. and C. W. Howes (1981).
The use of neighbouring plot values in the analysis of variety trials.
Applied Statistics, 30, 59--70.
http://doi.org/10.2307/2346657

Kerr, H. W. (1939). Notes on plot technique.
Proc. Internat. Soc. Sugarcane Technol. 6, 764-778.

Khin, San. 1950.
Investigation into the relative costs of rice experiments based on the efficiency of designs.
Dissertation: Imperial College of Tropical Agriculture (ICTA).
Appendix XV.
http://hdl.handle.net/2139/42422

Kiesselbach, Theodore A. (1917).
Studies Concerning the Elimination of Experimental Error in Comparative Crop Tests.
University of Nebraska Agricultural Experiment Station Research Bulletin No. 13.
Pages 51-72.
https://archive.org/details/StudiesConcerningTheEliminationOfExperimentalErrorInComparativeCrop
http://digitalcommons.unl.edu/extensionhist/430/

Kristensen, R. K. (1925). 
Anlaeg og Opgoerelse af Markforsoeg.
Tidsskrift for landbrugets planteavl, Vol 31, 464-494.
Fig 1, pg. 467.
http://dca.au.dk/publikationer/historiske/planteavl/ 

Kulkarni, R. K., Bose, S. S., and Mahalanobis, P. C.  (1936).
The influence of shape and size of plots on the effective precision of field experiments with sorghum. 
Indian J. Agric. Sci., 6, 460-474. Appendix 1, page 172.
https://archive.org/details/in.ernet.dli.2015.271737

Lander, P. E. et al. (1938).
Soil Uniformity Trials in the Punjab I.
Ind. J. Agr. Sci. 8:271-307.

Laycock, D. H. (1955).
The effect of plot shape in reducing the errors of tea experiments.
Tropical Agriculture, 32, 107-114.

Department of Agriculture, Mysore State.
[2nd-9th] Annual Report of the Agricultural Chemist. 
https://books.google.com/books?id=u_dHAAAAYAAJ

Lessman, Koert James (1962).
Comparisons of methods for testing grain yield of sorghum.
Iowa State University.
Retrospective Theses and Dissertations. Paper 2063. Appendix Table 17.
https://lib.dr.iastate.edu/rtd/2063

Li, HW and Meng, CJ and Liu, TN. 1936.
Field Results in a Millet Breeding Experiment.
Agronomy Journal, 28, 1-15.  Table 1.
http://doi.org/10.2134/agronj1936.00021962002800010001x

Loesell, Clarence (1936). 
Size of plot & number of replications necessary for varietal trials with white pea beans.
Thesis, Michigan State.
https://d.lib.msu.edu/etd/5271

Lord, L. (1931).
A Uniformity Trial with Irrigated Broadcast Rice.
The Journal of Agricultural Science, 21(1), 178-188.
https://doi.org/10.1017/S0021859600008029

Love, Harry (1937).
Application of Statistical Methods to Agricultural Research.
The Commercial Press, Shanghai. Page 411.
https://archive.org/details/in.ernet.dli.2015.233346/page/n421

Lucas, HL. 1956.
Switchback trials for more than two treatments.
Journal of Dairy Science, 39, 146-154.
http://doi.org/10.3168/jds.S0022-0302(56)94721-X

Lyon, T.L. (1911).
Some experiments to estimate errors in field plat tests.
Proc. Amer. Soc. Agron, 3, 89-114. Table III.
http://doi.org/10.2134/agronj1911.00021962000300010016x

Magistad, O. C.; & C. A. Farden (1934).
Experimental Error In Field Experiments With Pineapples.
Journal of the American Society of Agronomy, 26, 631--643.

Masood, M Asif and Raza, Irum. 2012.
Estimation of optimum field plot size and shape in paddy yield trial.
Pakistan J. Agric. Res., Vol. 25 No. 4, 2012

McClelland, Chalmer Kirk (1926).
Some determinations of plat variability.
Agronomy Journal, 18, 819-823.
http://doi.org/10.2134/agronj1926.00021962001800090009x

Mercer, WB and Hall, AD, 1911. The experimental error of field trials
The Journal of Agricultural Science, 4, 107-132. Table 1.
http://doi.org/10.1017/S002185960000160X

Montgomery, E. G. (1912).
Variation in Yield and Methods of Arranging Plats To Secure
Comparative Results.
Twenty-Fifth Annual Report of the Agricultural Experiment Station of Nebraska, 164-180.
https://books.google.com/books?id=M-5BAQAAMAAJ&pg=RA4-PA164
  
E. G. Montgomery (1913).
Experiments in Wheat Breeding: Experimental Error In The Nursery and
Variation in Nitrogen and Yield.
U.S. Dept of Agriculture, Bureau of Plant Industry, Bulletin 269.
Figure 10, page 37.
http://doi.org/10.5962/bhl.title.43602

Moore, John F and Darroch, JG. (1956).
Field plot technique with Blue Lake pole beans, bush beans, carrots,
sweet corn, spring and fall cauliflower.
Washington Agricultural Experiment Stations, Institute of Agricultural Sciences, State College of Washington.

Nagai, Violeta (1978).
Tamanho da parcela e numero de repeticoes em experimentos com morangueiro (Plot size and number of repetitions in experiments with strawberry).
Bragantia, 37, 71-81. Table 2, page 75.
http://dx.doi.org/10.1590/S0006-87051978000100009

Nair, B. Gopakumaran Nair, (1984).
Optimum plot size for field experiments on turmeric (Curcuma longa L)
Thesis, Department of Statistics, College of Veterinary & Animal Sciences, Mannuthy.
http://krishikosh.egranth.ac.in/handle/1/5810147397
Appendix has data.

Narain, R.; and A. Singh, (1940).
A Note on the Shape of Blocks in Field Experiments.
Ind. J. Agr. Sci., 10, 844-853. Page 845.
https://archive.org/stream/in.ernet.dli.2015.271745

Nonnecke, Ib Libner. (1958).
Yield variability of sweet corn and canning peas as affected by plot size and shape.
Thesis at Oregon State College.
http://hdl.handle.net/1957/23367

Obsi, Dechassa (2008).
Application of Spatial Modeling to the Study of Soil Fertility Pattern.
MS Thesis, Addis Ababa University. Page 122-125.
http://etd.aau.edu.et/handle/123456789/3221

Odland, TE and Garber, RJ. (1928).
Size of Plat and Number of Replications in Field Experiments with
Soybeans.
Agronomy Journal, 20, 93--108.
http://doi.org/10.2134/agronj1928.00021962002000020002x

Paez Bogarin, Gilberto (1962).
Estudios sobre tamano y forma de parcela para ensayos en cafe.
Instituto Interamericano de Ciencias Agricolas de la O.E.A. Centro Tropical de Investigacion y Ensenanza para Graduados. Costa Rica.
http://hdl.handle.net/11554/1892

Panse, V. G. (1941).
Studies in the technique of field experiments. V. Size and shape of
blocks and arrangements of plots in cotton trials. 
The Indian Journal Of Agricultural Science, 11, 850-867
https://archive.org/details/in.ernet.dli.2015.271747/page/n955

Parker, E. R.; & L. D. Batchelor. (1932).
Variation in the Yields of Fruit Trees in Relation to the Planning of Future Experiments.
Hilgardia, 7(2), 81-161. Tables 3-9.
http://doi.org/10.3733/hilg.v07n02p081

Polson, David (1964).
Estimation of Optimum Size, Shape, and Replicate Number of Safflower Plots for Yield Trials.
Utah State University, All Graduate Theses and Dissertations, 2979.
Table 6.
http://digitalcommons.usu.edu/etd/2979

Robinson, H.F.; and J.A.Rigney and P.H.Harvey (1948).
Investigations In Peanut Plot Technique With Peanuts.
Univ California Tech. Bul. No 86.

Rothamsted Experimental Station, Report 1925-26.
Lawes Agricultural Trust, p. 154-155.
http://www.era.rothamsted.ac.uk/eradoc/book/84

Sayer, Wynne; M. Vaidyanathan and S. Subrammonia Iyer (1936).
Ideal size and shape of sugar-cane experimental plots based upon tonnage experiments with Co 205 and Co 213 conducted in Pusa.
Indian J. Agric. Sci., 1936, 6, 684-714. Appendex, page 712.
https://archive.org/details/in.ernet.dli.2015.271737
  
Sayer, Wynne; and Krishna Iyer.  (1936).
On some of the factors that influence the error of field experiments with special reference to sugar cane.
Indian J. Agric. Sci., 1936, 6, 917-929. Appendix, page 927.
https://archive.org/details/in.ernet.dli.2015.271737

Shafi, Sameera (2007).
On Some Aspects of Plot Techniques in Field Experiments on Tomato (Lycopersicon esculentum mill.) in Soils of Kashmir.
Thesis. Univ. of Ag. Sciences & Technology of Kashmir. Table 2.2.1.
http://krishikosh.egranth.ac.in/handle/1/5810083035

Shafi, Sameera; S.A.Mir, Nageena Nazir, and Anjum Rashid. (2010).
Optimum plot size for tomato by using S-PLUS and R-software's in the soils of Kashmir.
Asian J. Soil Sci., 4, 311-314.
http://www.researchjournal.co.in/upload/assignments/4_311-314.pdf

Smith, Francis L. (1958).
Effects of plot size, plot shape, and number of replications on the
efficacy of bean yield trials.
Hilgardia, 28, 43-63.
http://doi.org/10.3733/hilg.v28n02p043

Smith, Louis H. 1910.
Plot arrangement for variety experiments with corn.
Agronomy Journal, 1, 84--89. Table 1.
http://books.google.com/books?id=mQT0AAAAMAAJ&pg=PA84

Stephens, Joseph C. 1928.
Experimental methods and the probable error in field experiments with sorghum.
Journal of Agricultural Research, 37, 629--646.
http://naldc.nal.usda.gov/catalog/IND43967516

Stickler, F. C. (1960).
Estimates of Optimum Plot Size from Grain Sorghum Uniformity Trial Data.
Technical bulletin, Kansas Agricultural Experiment Station.

Strickland, A. G. (1935).
Error in horticultural experiments.
Journal of Agriculture, Victoria, 33, 408-416.
http://handle.slv.vic.gov.au/10381/386642

A. G. Strickland (1932).
A vine uniformity trial.
Journal of Agriculture, Victoria, 30, 584-593.
http://handle.slv.vic.gov.au/10381/386462

A. G. Strickland (1935).
Error in horticultural experiments.
Journal of Agriculture, Victoria, 33, 408-416.
http://handle.slv.vic.gov.au/10381/386642

Wassom and R.R. Kalton. (1953).
Estimations of Optimum Plot Size Using Data from Bromegrass Uniformity
Trials. Agricultural Experiment Station, Iowa State College, Bulletin 396.
http://lib.dr.iastate.edu/ag_researchbulletins/32/

Wiebe, G.A. 1935.
Variation and Correlation in Grain Yield among 1,500 Wheat
Nursery Plots.
Journal of Agricultural Research, 50, 331-357.
http://naldc.nal.usda.gov/download/IND43968632/PDF

Wiedemann, Alfred Max. 1962.
Estimation of Optimum Plot Size and Shape for Use in Safflower Yield Trails. Table 5.
All Graduate Theses and Dissertations. Paper 3600. Table 5.
http://digitalcommons.usu.edu/etd/3600

Williams, ER and Luckett, DJ. 1988.
The use of uniformity data in the design and analysis of cotton and barley variety trials.
Australian Journal of Agricultural Research, 39, 339-350.
http://doi.org/10.1071/AR9880339

F. A. Wyatt (1927).
Variation in plot yields due to soil heterogeneity.
Scientific Agriculture, 7, 248-256. Table 1.
https://doi.org/10.4141/sa-1927-0020



------------------------------------------------------------------------------


# Reviewed. Not used.


Damor, Bhavika. (2019).
Comparison of uniformity trial data with experimental data for plot technique.
DEPARTMENT OF AGRICULTURAL STATISTICS B. A. COLLEGE OF AGRICULTURE ANAND AGRICULTURAL UNIVERSITY ANAND.
https://krishikosh.egranth.ac.in/handle/1/5810169594
Has data for 3 uniformity trials, but the data look strange. For example, in Appendix III, there are some plots along the left edge that are measured to 3 decimals (0.993, 0.631), but most of the field is measured to 2 decimals. In Appendix I, there are 500 numbers but only about 9 of them have "4" in the hundredths place. We would expect to see 50. It could be that the data were collected in non-kg weights and then converted to kg. It could be that the html-viewer is not rendering the document correctly, but there is no way to download the original pdf.


Hansen, Niels Anton (1914).
Provedyrkning paa Forsogsstationen ved Aarslev.
Tidsskrift for landbrugets planteavl.
http://dca.au.dk/publikationer/historiske/planteavl/ 
Bind 21, page 553. In Danish. Page 557 might be the table referred to by Eden, except there are 30 plots, not 35. Yields appear to be given as percents.
See comments by Eden & Maskell found here:
https://archive.org/stream/in.ernet.dli.2015.25895/2015.25895.Journal-Of-Agricultural-Science-Vol-xviii-1928#page/n175
Page 165: "One of the trials, comprising 35 plots, extended over the years 1907-11 and included oats, rye, barley, roots, barley."
Oats and rye 1907 and 1908 show marked positive correlation.
rye and barley 1908 and 1909 no correlation of significance.
barley and roots 1909 and 1910 no correlation.
roots and barley 1910 and 1911 a significant correlation.
rye and roots 1908 and 1910 satisfactory.


Hatton, R. G.; N. H. Grubb & R. C. Knight (1928) 
Black Currant Variety Trials: Reliability of Results., 
Journal of Pomology and Horticultural Science, 4:4, 200-220.
https://doi.org/10.1080/03683621.1925.11513282
Not used. Has data for 21 bushes * 4 years and 52 bushes * 4 years.


Lambert, Edmund B. (1934).
Size and arrangement of plots for yield tests with cultivated mushrooms.
Journal of Agricultural Research, Vol 48, 971-980.
Note: Uniformity trial at three locations for mushrooms in growth houses.
https://naldc.nal.usda.gov/naldc/download.xhtml?id=IND43968493


# Reviewed. No data found.

Bakke, Olaf Andreas. (1988).
Tamanho e forma ótimos de parcelas em delineamentos experimentais.
Dissertation. Escola Superior de Agricultura Luiz de Queiroz.
https://teses.usp.br/teses/disponiveis/11/11134/tde-20181127-160559/pt-br.php
Used Gomez rice uniformity.


Bayoumi, Tarek Youssef;  S El-Demardash.
Effect of water deficit on soil variability, plot size, shape and number of replications for chickpea.
No data.


Beard, J.S. (1954).
Investigations into experimental plot technique with black wattle.
Empire Forestry Review, 33, 158-171.
https://www.jstor.org/stable/42602653
No data.


Bhatt, Hitesh M. (1998). 
"Plot technique in Potato".
AAU, Anand.
https://krishikosh.egranth.ac.in/handle/1/5810043200
No data.


Bose, S S; Khanna, K L; Mahalanobis, P C
Note on the optimum shape and size of plots for sugarcane experiments in Bihar.
India Journal of Agricultural Science 9, 807-816
http://hdl.handle.net/10263/1896
No data.


Boyhan, George E.; David B. Langston; Albert C. Purvis; C. Randell Hill. (2003).
Research to determine suitable plot size and the number of replications in the field trials of sugarbeet.
J. Amer. Soc. Hort. Sci., 128, 409-424.
https://journal.ashs.org/downloadpdf/journals/jashs/128/3/article-p409.pdf
No data. Compared Hatheway's method with Cochran and Cox's method, the latter gave smaller number of plots.


Boyhan, George E. (2013).
Optimum Plot Size and Number of Replications for Determining Watermelon Yield, Fruit Size, Fruit Firmness, and Soluble Solids.
HortScience, 48, 1200-1208.
https://doi.org/10.21273/HORTSCI.48.9.1200
https://journals.ashs.org/hortsci/view/journals/hortsci/48/9/article-p1200.xml
No data.


Brim, C. A. and D. D. Mason. (1959).
Estimates of Optimum Plot Size for soybean Yield Trials. 
Agron. Jour. 51: pp. 331-335·
http://doi.org/10.2134/agronj1959.00021962005100060008x
No data.


Chaves, L. J.; J. B. Miranda Filho (1992).
Plot size for progeny selection in maize (Zea maysL.).
Theoretical and Applied Genetics, 84, 963–970.
https://doi.org/10.1007/bf00227411
No data.


Cheesman, E.  E., and Pound, F. J.
"Uniformity trials on Cacao".
Trop. Agric., 9, 277-88. 
No data.


Conners, Helen Elizabeth (1951). 
Field plot techniques for sweet potatoes obtained from uniformity trial data.
Master's Thesis, Iowa State University.
No digital copy available.
No data.


Cordeiro, Célia Maria Torres, João Eustáquio Cabral de Miranda, and Jarbas Campos. 
"Tamanho de parcelas e número de repetições em experimento de batatas." 
Pesquisa Agropecuária Brasileira 17.9 (1982): 1341-1348.
No data.


Crews, Julian W., Guy L. Jones, and D. D. Mason. 
"Field Plot Technique Studies with Flue‐Cured Tobacco. I. Optimum Plot Size and Shape 1." Agronomy Journal 55.2 (1963): 197-199.
No data.


da Silva, Willerson  Custódio; Mário  Puiatti; Paulo  Roberto  Cecon; Leandro  Roberto  de  Macedo;  Tocio  Sediyama. (2019)
Estimation of optimum experimental plot size for taro culture.
Ciência Rural, Santa Maria, v.49
http://dx.doi.org/10.1590/0103-8478cr20180440
No data.


da Silva, Luiz Fernando de Oliveira; Katia Alves Campos; Augusto Ramalho de Morais; Franciane Diniz Cogo; Carolina Ruiz Zambon.
Optimal plot size for experiments with radish.
Revista Ceres 59(5):624-629
http://doi.org/10.1590/S0034-737X2012000500007
No data.


de Sousa, Roberto Pequeno; Paulo Sérgio Lima e Silva; Janilson Pinheiro de Assis; Paulo Igor Barbosa e Silva; Júlio César DoVale. 2015.
Optimum plot size for experiments with the sunflower.
Revista Ciencia Agronomica, 46, 170-175.
DOI: 10.1590/S1806-66902015000100020
No data.  Precision increased up to plot sizes about 5 m^2.


Dorph-Petersen, K. 1949. 
Parcelfordeling i markforsog. 
Tidsskrift for Planteavl. 52, 111-175
https://dca.au.dk/publikationer/historiske/planteavl/
No data. Did not see anything that looked like a field of 12x43 plots.
Mentioned in Kristensen (2003).


Elliot, F. C., Darroch, J.G. and Wang, H.L. (1952). 
Uniformity trials with spring wheat. 
Agronomy Journal, 44, 524-528.
https://doi.org/10.2134/agronj1952.00021962004400100005x


Facco, Giovani; Cargnelutti Filho Alberto; Mendonça Alves Bruna; et. al. February 2017.
Basic experimental unit and plot sizes with the method of maximum curvature of the coefficient of variation in sunn hemp.
African journal of agricultural research 12(6):415-423
DOI: 10.5897/AJAR2016.11814
No data.


Filho, Alberto;  Cargnelutti; Marcos  Toebe; Cláudia  Burin; André  Luis  Fick; Gabriele  Casarotto. (2011).
"Plot sizes and uniformity assays in turnip."
Ciência Rural 41.9 (2011): 1517-1525.
https://doi.org/10.1590/S0103-84782011005000119
No data.


Filho, Alberto Cargnelutti; Marcos Vinícius Loregian, Gabriel Elias Dumke, Felipe Manfio Somavilla, Samanta Luiza da Costa, Lucas Fillipin Osmari, Bruno Fillipin Osmari (2021).
Optimal plot size in buckwheat.
http://dx.doi.org/10.5433/1679-0359.2021v42n2p501
http://www.uel.br/revistas/uel/index.php/semagrarias/article/view/39448/29330
No data


Fleming, A.A., Roger, T.H. and Bancroft, T.A. (1957).
Field plot technique with hybrid corn under Alabama conditions.
Agronomy Journal, 49, 1-4.
https://doi.org/10.2134/agronj1957.00021962004900010001x


George, M. V.; M. Sannamarappa (1984).
Uniformity trial: Size, Shape, and Direction of Experimental Plots for Turmeric.
Proceedings of the Sixth Symposium on Plantation Crops, p. 429.
https://archive.org/details/in.ernet.dli.2015.502074/page/n453
No data.


Gopalakrishna, S. (1992).
Optimum plot size and shape, block size and shape and relative efficiency of designs for field experiments in navane (Setaria italica).
Thesis.
http://krishikosh.egranth.ac.in/handle/1/5810120871
No data.


Goyal, Manoj Kumar. 1998.
A Study of uniformity trial in wheat (Triticum aestivum L.).
College of Agriculture Chaudhary Charan Singh Haryana Agricultural University Hisar.
https://krishikosh.egranth.ac.in/handle/1/5810078304 .
No data.


Guimarães, Bruno Vinícius Castro, et al. (2020).
"Optimal plot size for experimental trials with Opuntia cactus pear."
Acta Scientiarum. Technology 42 (2020): e42579-e42579.
https://doi.org/10.5539/jas.v11n18p206
No data.


Gupton, C.L. (1972).
Estimates of Optimum Plot Size and Shape from Uniformity Data in Burley Tobacco (Nicotiana tabacum L.).
Agron J, 64, 678-682. 
https://doi.org/10.2134/agronj1972.00021962006400050038x
No data.


Handa, D. P.; Sreenath, P. R., & Rajpali, S. K. (1995). 
Uniformity trial with lucerne grown for fodder. 
Grass and Forage Science, 50(3), 209–216. 
http://doi.org/10.1111/j.1365-2494.1995.tb02316.x 
No data.


Hariharan, V., Jacob Thomas, M. George, K.C. (1986).
Optimum size and shape of plots for field experiments in brinjal.
Agricultural Research Journal of Kerala, 24(2), 189-194.
http://krishikosh.egranth.ac.in/handle/1/5810100010
No data.


Hatheway, W. H., and E. J. Williams. (1958).
"Efficient estimation of the relationship between plot size and the variability of crop yields."
Biometrics, 14, 207-222.
https://doi.org/10.2307/2527785
No data.


Heidmann, T. 1988. 
Startkarakterisering af arealer til systemforskning I.  Forsøgsarealer, måleprogram og metoder.
Tidsskrift for Planteavls Specialserie. S 1958, 89 pp.
https://dca.au.dk/publikationer/historiske/planteavlspecial/
No data. No obvious data found for a field 26x20 plots.
Mentioned in Kristensen (2003).


Heidmann, T. 1989.
Startkarakterisering af arealer til systemforskning: IV Resultater fra arealet ved Jyndevad.
Tidsskrift for Planteavls Specialserie. S 2021, 163 pp.
https://dca.au.dk/publikationer/historiske/planteavlspecial/
No data. No obvious data found for a field 26x20 plots.
Mentioned in Kristensen (2003).


Hidalgo, Eduardo Calero Calero (1965).
Estudio Del Tamano Y Forma De La Parcela Experimental Para Ensayos De Campo En Frijol (Phaseolus vulgaris L.).
Instituto Interamericano de Ciencias Agricolas de la OEA.
http://hdl.handle.net/11554/1827
No data. In Spanish.


Hodnett, G.E. 
A Uniformity Trial on Groundnuts.
Journal of Agricultural Science.
https://www.cambridge.org/core/journals/journal-of-agricultural-science/article/uniformity-trial-on-groundnuts/0BE0B311FACEA593803F68180AF08452
No data.


Holle, Michael. 1960.
Plot technique for field evaluation of three characters in the lima bean.
Master's Thesis, Iowa State University. 
No digital copy available.
No data. 


Idrees, Nadia; and Muhammad Inayat Khan (2009).
Design improvement using uniformity trials experimental data.
Pak. J. Agri. Sci., Vol. 46(4), 2009.
http://www.pakjas.com.pk 
No data.


Johnson, I.J. & Murphy, H.C. 1943.
Lattice and lattice square designs with oat uniformity data and in varietal trials.
J. Agric. Sci., 22, 366-372.
https://doi.org/10.2134/agronj1943.00021962003500040004x
No data. Has a contour map of fertility.


Jones, W.W.; T.W. Embleton; C.B. Cree. (1957).
Number of Replications and Plot Sizes Required for Reliable Evaluation of Nutritional Studies and Yield Relationships with Citrus and Avocado.
American Society for Horticultural Science, 69:208-216.
No data. Fruit yields are much more variable than quality factors.


Jua, Junagadh.
Optimum plot size for field experiments on tomato – A statistical investigation.
Thesis, Junagadh Agricultural University.
http://krishikosh.egranth.ac.in/handle/1/5810006490.
No data.


Kaushik, L. S., R. P. Singh, and T. P. Yadava. 
"A uniformity trial with mustard [India]." 
Indian Journal of Agricultural Sciences (1977).
No data.


Kavitha, B. (2010).
Study on optimum plot size and optimum plot shape of soybean crop.
http://krishikosh.egranth.ac.in/handle/1/84302
No data.


Keller, Kenneth R. (1949).
Uniformity Trial on Hops, Humulus lupulus L., for Increasing the Precision of Field Experiments.
https://doi.org/10.2134/agronj1949.00021962004100080011x
No data.


Khurana, Alka. 1991.
A Study of Uniformity Trial in Soyabean.
Thesis, M.Sc.
College of Basic Sciences and Humanities Chaudhary Charan Singh Haryana Agricultural University Hisar.
https://krishikosh.egranth.ac.in/handle/1/5810076525
No data. Smith's Law.


Kristensen, Dr. K. (2003).
Incomplete split-plots in variety trials - based on a-designs. 
In: Biuletyn Oceny Odmian, 31, pp. 7-17. 
No data. Refers to other papers with uniformity trials.


Krysczun, Dionatan Ketzer; Lúcio, Alessandro Dal’Col; Sari, Bruno Giacomini; Diel, Maria Inês; Olivoto, Tiago; Santana, Cinthya Souza; Ubessi, Cassiane; Schabarum, Denison Esequiel  (2018).
Sample size, plot size and number of replications for trials with  Solanum melongena  L.. Scientia Horticulturae, 233(), 220–224.
doi:10.1016/j.scienta.2018.01.044
No data.


Kumar, Ajay. 1999.
A study on uniformity trial in sesame (Til) Sesamum indicum.
http://krishikosh.egranth.ac.in/handle/1/5810078711.
No data.


Kumar, Ajay; Kiran Kapoor; Gupta, S. C.; Hasija, R. C.
Uniformity trial on sesame Sesamum indicum.
https://eurekamag.com/research/017/592/017592269.php
Not found, but Kumar's thesis was found, but had no data.


Lakhera, M.L.; M.A. Ali (1996).
Optimum plot size and shape estimates for sunflower yield trials.
Journal of Maharashtra Agricultural Universities 21(3): 350-353
http://14.139.56.90/displaybitstream?handle=1/65373
No data. Optimum plot size was 20 units, 10 rows each 2 m long.


Lavezo, André; Alberto Cargnelutti Filho, Cláudia Marques de Bem, Cláudia Burin, 
Jéssica Andiara Kleinpaul, Rafael Vieira Pezzini.
Plot size and number of replications to evaluate the grain yield in oat cultivars.
Bragantia, Campinas, v. 76, n. 4, p.512-520, 2017.
http://dx.doi.org/10.1590/1678-4499.2016.410
No data.


Lizy, M.J. (1986).
Uniformity trials on colocasia.
http://krishikosh.egranth.ac.in/handle/1/5810113181
No data.


Lizy, M.J.; George, K.C.; Thomas, M.J. (1988).
Optimum size and shape of plots under colocasia (Colocasia esculenta L.)
Agricultural Research Journal of Kerala 25(2): 241-248
https://eurekamag.com/research/001/901/001901914.php
Paper not found, but Lizy thesis was found, but had no data.


Lohmor, Nishu (2015).
Estimation of optimum plot size, shape and number of replications in sunflower (Helianthus annuus).
Thesis.
http://krishikosh.egranth.ac.in/handle/1/81261
No data.

Lohmor, Nishu; Mujahid Khan; Kiran Kapoor; and Nitin Tanwar (2017).
Study on Optimum Block Size and Shape in Uniformity Trial of Sunflower (Helianthus annuus). 
Advances in Research, 9, 1-8. 2017.
No data.


Lorentz, Leandro Homrich; Alexandra Augusti Boligon; Lindolfo Storck; Alessandro Dal'Col Lúcio.
Plot size and experimental precision for sunflower production.
Sci. Agric. (Piracicaba, Braz.), v.67, n.4, p.408-413, July/August 2010
No data.


Meier, V. D., and K. J. Lessman. 
"Estimation of Optimum Field Plot Shape and Size for Testing Yield in Crambe abyssinica Hochst". 
Crop Science 11, 648-650.
https://doi.org/10.2135/cropsci1971.0011183X001100050013x
No data.


Miller, John D., and E. James Koch. (1962)
"A Plot Technique Study with Birdsfoot Trefoil 1."
Agronomy Journal, 54, 95-97.
https://acsess.onlinelibrary.wiley.com/doi/abs/10.2134/agronj1962.00021962005400020001x
No data.


Miyaska, Susan C.; Charles E. McCulloch, Graham E. Fogg, James R. Hollyer.
Optimum Plot Size for Field Trials of Taro (Colocasia esculenta).
HortScience 48, 435-443.
https://doi.org/10.21273/HORTSCI.48.4.435 
No data. Optimum plot size was 18-21 plants (4.9 - 5.7 m^2).


Modjeska, J. S., & Rawlings, J. O. (1983). 
Spatial Correlation Analysis of Uniformity Data. 
Biometrics, 39(2), 373. 
http://doi.org/10.2307/2531010 
Used data from Batchelor & Reid.


Muniya, Sejal ben.
Plot size study through mathematical approach.
https://krishikosh.egranth.ac.in/handle/1/5810115216
No data.


Nagardas, Motaka Ganapatlal (2006).
PLOT SIZE STUDY FROM UNIFORMITY TRIAL DATA IN DURUM WHEAT FOR BHAL REGION.
http://krishikosh.egranth.ac.in/handle/1/5810115906
No data.


Narayanan, R (1974).
Estimation of optimum plot size for clone trials in hevea.
Journal of the Rubber Research Institute of Malaysia 24(1): 54-67.
http://rios.lgm.gov.my/cms/fedDigiJournalDetail.jsp?searchText=&selTab=digiCon&id=&type=JRR&issueYear=1974
No data.


Narayanbhai, P.J. (2005).
Plot size study from uniformity trial data of French bean.
http://krishikosh.egranth.ac.in/handle/1/5810115923
No data.


Oliveira, Sérgio José Ribeiro de. 
Dependência entre o tamanho da unidade básica e as estimativas das dimensões da parcela experimental de batata. 
Diss. Universidade Federal de Santa Maria, 2005.
No data.


Omanakuttan, Chithra (2015).
Plot size study from uniformity trial data of mustard (Brassica juncea L.).
http://krishikosh.egranth.ac.in/handle/1/5810116905
No data.


Onate, Burton. 1965.
Size and Shape of Plot in Rice Replicated Field Experiments.
Philippine Statistician.
http://k-archive.pssc.org.ph/handle/0/2096
No data. Results indicate that plot of dimensions 4 rows by 12 hills (3-5 sq m) will be relatively as efficient as bigger plots. The CV observed was about 10 percent, which implies 5 replicates are needed to detect a mean difference of 10 percent.


Paardekooper, E.G. (1966). 
Results of four uniformity trials to determine the influence of plot size and shape on the efficiency of field experiments in rubber.
Res. At-chs Rubb. Res. Inst. Malaya, Docum. 56.
No data.

Pal, Satyabrata; Goutam Mandal; Kajal Dihidar. 2015.
Determination of robust optimum plot size and shape – a model-based approach.
Biometrical Letters, 52, 13-22.
http://pldml.icm.edu.pl/pldml/element/bwmeta1.element.doi-10_1515_bile-2015-0002
No data.


Patel, J.B. (2004).
Estimation of Optimum Plot Size for Field Experiment on Green Gram (Phaseolus rediatus L.)
http://krishikosh.egranth.ac.in/handle/1/5810072537
No data.


Patel, Natverlal M. (1967).
Plot technique in Bajri-Pennisetum typhoides.
https://krishikosh.egranth.ac.in/handle/1/5810045227
No data.


Patel, N.M. (1981).
Plot size study in bidi tobacco (Nicotiana tabacum L.).
Thesis.
http://krishikosh.egranth.ac.in/handle/1/5810045267
No data.


Patil, N.M. (1995).
Optimum plot size and shape, block size and shape and relative efficiency of designs for field experiments in cowpea (Vigna unguiculata).
http://krishikosh.egranth.ac.in/handle/1/5810119241
No data.


Peiris, T. S. G.;  and R. O. Thattil (1997).
Alternative methods to determine plot sizes for three crops: A case study from coconut data.
COCOS (1997), 12, 44-53 
No data. References CRI (1985).


Pimentel, Gomes; Couto, H.T.Z. (1985).
O Tamanho Ótimo de Parcela Experimental Para Ensaios com Eucaliptos (The  Optimum Experimental Plot  Size for Essays with  Eucalipt).
Revista do  IPEF,  Pirarcicaba, 31,  75.
No data.


Plaisted, Robert LeRoy (1954).
Field plot techniques for estimating onion yields.
Master's Thesis, Iowa State University.
https://doi.org/10.31274/rtd-20200617-42
No data.


Prabhakaran, P.V. (1978).
Optimum plot size for field trials with banana.
Agricultural Research Journal of Kerala, 16(1), 33-38.
http://krishikosh.egranth.ac.in/handle/1/5810115813
No data.


Prajapati Rameshbhai, I. (2005).
Optimum size and shape of plot for field experiments on potato.
Thesis.
http://krishikosh.egranth.ac.in/handle/1/5810115905
No data.


Ramani, C.V. (1995).
Plot technique in Lucern.
http://krishikosh.egranth.ac.in/handle/1/5810046435
No data.


Reddy, M. N., and C. K. Ramanatha Chetty
Effect of Plot Shape on Variability in Smith's Variance Law.
Experimental Agriculture, 18, 333-338.
https://doi.org/10.1017/S0014479700000752
No data.


Reddy, S.B.S. (1992).
Uniformity trial on groundnut.
http://krishikosh.egranth.ac.in/handle/1/5810000021
No data for the uniformity trial? Small dataset on page 96, 20 plots with 5 plants/plot. Branches/plant, leaves/plant, height of the plant. 


Ross C. Thompson (1934).
Size, Shape, and Orientation of Plots and Number of Replications Required in Sweetpotato Field-Plot Experiments.
J. Agric. Rsch., 5, 
https://books.google.com/books?hl=en&lr=&id=9-DUAAAAMAAJ&oi=fnd&pg=PA379
No data. Interesting paper because the experiment was conducted on 4 plots of year/loc combinations.


Rossettii, A.G.; Pimentel Gomes, F. (1983).
Determinação do Tamanho Otimo de Parcelas em Ensaios Agricolas (Determination of the  Optimum  Plot  Size  in Agricultural  Essays).
Pesq.  agropec.  bras.,  Brasilia,  18(5), 477.
No data. In Spanish.


Rossetti, A.G.; Gomes, F.P. (1987).
A method for the determination of optimum plot size in experiments with rubber trees (Hevea).
J Nat Rubb Res (1987) 2(3):135-141 
http://rios.lgm.gov.my/cms/fedDigiContentDetail.jsp?searchText=&selTab=digiCon&id=vital1:24082&type=Article
No data.


Sagisi, Fancisca D.; Mariano B. de Ramos.
Field Plot and Sampling Techniques on Virginia Tobacco.
http://k-archive.pssc.org.ph/bitstream/handle/0/2407/07_Field%20Plot%20and%20Sampling%20Tecniques%20On%20Virginia%20Tobacco.pdf
No data for the uniformity trial part of this report.


Sands, Daniel E. (1954).
A Determination of Optimum Plot Size for Estimating Mean Number of Bolls.
USDA. http://www.nass.usda.gov/Education_and_Outreach/Reports,_Presentations_and_Conferences/Yield_Reports/A%20Determination%20of%20Optimum%20Plot%20Size%20for%20Estimating%20Mean%20Number%20of%20Bolls.pdf
No data.


Sari, Bruno Giacomini; Alessandro Dal'Col Lucio. (2018).
Uniformity trials size for estimating cherry tomato plot size.
Revista Ciência Agronômica, v. 49, n. 4, p. 653-662, out-dez, 2018
http://ccarevista.ufc.br/seer/index.php/ccarevista/article/view/4462
No data.


Schmildt, Edilson Romais; Adriel Lima Nascimento; Alan de Lima Nascimento; et al.
Optimum plot size for experiments with papaya genotypes in field.
African Journal of Agricultural Research, 13, 360-365.
DOI: 10.5897/AJAR2017.12951 
No data. Optimum plot size if four plants by plot, using four replications.


Sharma, Anju (1992).
Determination of optimum plot size estimation of of tomato (Lycopersicon esculentum Mill.) yield in Saproon Valley of Solan District (H.P.).
http://krishikosh.egranth.ac.in/handle/1/5810067799
No data.


Sharpe, R. H., and G. H. Blackmon, 1950
"A Study of Plot Size and Experimental Design with Pecan Yield Data." 
Am. Soc. Hort. Sci. Pro. 56:236-241.
No data.


Sheela, M A (1987).
Optimum size of plots in cocoa (Theobroma cacoa L.) a multivariate case.
Department of Statistics, College of Veterinary and Animal Sciences, Mannuthy
http://krishikosh.egranth.ac.in/handle/1/5810142527
No data.


Shitap, Shri M.S. (2011).
Plot technique in Brinjal (Solanum melongena L.)
http://krishikosh.egranth.ac.in/handle/1/5810010600
No data.  The table of contents suggests that the data appears in the appendix, but the pages are blank.


Siao, F.U. 1935.
Uniformity trials with cotton.
J. Amer. Soc. Agron., 27, 974-979.
https://doi.org/10.2134/agronj1935.00021962002700120004x
No data.


Sills, G. R., & Nienhuis, J. (1993).
Field Plot Technique Affects Snap Bean Yield Evaluation.
Journal of the American Society for Horticultural Science, 118(5), 672-674. https://doi.org/10.21273/JASHS.118.5.672
No data.


Sokhal, Urmil (1982).
College on The Efficiency of Designs for Bajra in Relation to Shape and size of Plot And Block.
http://krishikosh.egranth.ac.in/handle/1/5810055172
No data. 
 
 
Soplin, H., H. D. Gross, and J. O. Rawlings. 
"Optimum Size of Sampling Unit to Estimate Coastal Bermudagrass Yield 1." 
Agronomy Journal 67.4 (1975): 533-537.
No data.


Stadler, Lewis John. (1921).
Experiments in field plot technic for the preliminary determination of comparative yields in the small grains.
University Of Missouri.
https://hdl.handle.net/2027/umn.319510008017444
No data. Uniformity trial discussed on page 43.


Storck, Lindolfo; Sidinei Lopes; Alessandro Dal'Col Lúcio; Alberto ​Cargnelutti Filho 2011.
Optimum plot size and number of replications related to selective precision.
Ciência Rural 41(3):390-396.
http://doi.org/10.1590/S0103-84782011000300005
https://www.researchgate.net/publication/270761907_Optimum_plot_size_and_number_of_replications_related_to_selective_precision
No data


Swallow, William H.; Todd C. Wehner (1986).
Optimum Plot Size Determination and Its Application to Cucumber Yield Trials.
Euphytica, 35, 421-432.
https://doi.org/10.1007/BF00021850
No data. For multiple-harvest yield trials, optimum plot sizes were estimated to be 6.4 to 10.3 m^2.


Tartaglia, FdL, Lúcio, A, Diel, MI, et al. 
Experimental Plan For Tests With Pea.
Agronomy Journal. 2021; 113: 1394–1406.
https://doi.org/10.1002/agj2.20575 
No data. 


Taye, Girma; Amsal Tarekegne; and D. G. Tanner. (2000). 
"Estimation of optimum plot dimensions and replication number for wheat experimentation in Ethiopia." 
African crop science journal 8.1 (2000): 11-23.
https://repository.cimmyt.org/handle/10883/2321
No data.


Taylor, F.W. (1907-1909).
The size of the experimental plot for field crops.
Proceedings annual Society of agronomy 1, 56-58.
https://acsess.onlinelibrary.wiley.com/doi/10.2134/agronj1907-1909.00021962000100010014x
No data.


Taylor, Howard Lewis (1951).
The effect of plot shape on experimental error.
Master's Thesis, Iowa State University. 
No digital copy available.
No data given. Used data from a corn uniformity trial, oats uniformity, and the data of Fairfield Smith. Smaller experimental errors were found for long narrow plots.


Tedin, Olof (1931). The Influence of Systematic Plot Arrangement upon the Estimate of Error in field Experiments. J. Agric. Science, 21, 191-208.
https://doi.org/10.1017/S0021859600008613
No data. Uses uniformity trials from other papers.


Toebe, Marcos, et al. (2020).
"Plot size and number of replications for ryegrass experiments."
Ciência Rural 50.1.
http://dx.doi.org/10.1590/0103-8478cr20190195
No data.


Westover, Kyle C. (1924).
The influence of plot size and replication on experimental error in field trials with potatoes.
Agricultural Experiment Station, West Virginia University, No. 189.
https://babel.hathitrust.org/cgi/pt?id=uiug.30112019921359&view=1up&seq=1
No data.


Wilson, Wendell W. (1970).
Texas Vegetable Remote Sensing Study, 1969 Determination of Optimum Plot Size and Shape for Estimation of Carrot Yield.
Research and Development Branch Standards and Research Division Statistical Reporting Service.
https://www.nass.usda.gov/Education_and_Outreach/Reports,_Presentations_and_Conferences/Yield_Reports/Texas%20Vegetable%20Remote%20Sensing%20Study%201969.pdf
No data found.


Yadav, Raj Pal. 1991.
Spatial Correlation Analysis of Uniformity Trial Data.
College of Basic Sciences and Humanities Chaudhary Charan Singh Haryana Agricultural University Hisar.
https://krishikosh.egranth.ac.in/handle/1/5810076755
No data.


Vallejo, Roger L.; VHumberto A. Mendoza. (1992).
Plot  Technique  Studies  on  Sweetpotato  Yield Trials.
J. AMER. Soc. HORT. SCI. 117(3):508-511.
No data.


Vargas-Rojas, Jorge Claudio. (2020).
Size and shape of the experimental unit in yield trials of Brachiaria , hybrid CIAT 3608.
https://www.semanticscholar.org/paper/Size-and-shape-of-the-experimental-unit-in-yield-of-Vargas-Rojas/e9964eca6ac42471aa44bc45e84bc376b02daf09
    

Warren, J.A. and Mendez, I. (1981).
Block Size and Orientation, and Allowance for Positional Effects, in Field Experiments.
Experimental Agriculture, 17, 17 - 24.
https://doi.org/10.1017/S0014479700011182
No data. Used a dozen existing datasets.

# Paper not found

Abraham, T.P. & Vachhani, M.V. 1964.
Investigations on field experimental techniques with rice crop
Indian J. Agric. Sci. 34, 152-165.


Agarwal, K.N. (1973). 
Uniformity trial of Apple. 
Indian Journal of horticulture. 30:525-528.
https://www.indianjournals.com/ijor.aspx?target=ijor:ijh&volume=30&issue=3and4&article=013
Paywall. Not available.


Agarwal, K.N. & Deshpande, M.R. 1967.
Size and shape of plots and blocks in field experiments with dibbled paddy.
Indian J. Agric. Sci., 37, 445-455.


Agarwal, K.N., Bavappa, K.V.A. and Khosla, R.K. (1968). 
A study of size and shape of plots and blocks an optimum number of experimental periods on arecanut. 
Indian Journal of Agricultural Sciences, 38, 444-460.
Article not found. Journal: http://epubs.icar.org.in/ejournal/index.php/IJAgS


Agnihotri, V. and Asrawal, M. C. 1996.
Size and shape of plots and blocks for field experiments with Eucalyptus in Shivalik Hills.
Indian Journal of Forestry, 19, 74-78.
Not found.


Ali, A.A.; Ammar, S.E.M.M.
Optimum plot size and shape for trials of maize.
Annals of Agricultural Science, Moshtohor 36(3): 1361-1372.
https://eurekamag.com/research/012/808/012808132.php
Not found. 


Bhatnagar, S.; Srivastava, O.P. and Lather, B. P. S.
Optimum size and shape of plot for mustard.
Annals of Agricultural Research.
Not found.


Bischoff, K.P.; Gravois, K.A.; Schexnayder, H.P.J.; Hawkins, G.L. (2001).
The effect of harvest method and plot size on the estimation of sugarcane yield.
Journal American Society of Sugar Cane Technologists 21: 51-60.


Bonazzi, A. (1933).
Errors in field experimentation with ratoon cane.
Asoc. de Tec. Azucareros Cuba, Proc 7: 32-40.
Looked hard, but could not find.  Original probably in Spanish. Full publisher: Asociación de Técnicos Azucareros de Cuba.


Calzada Benza, J. 1957.
El error experimental y la precision en los experimentos. 
Lima  Peru , Estac. Expt. Agr. de La Molina , Bol. 67 , 33 pp .
Not found.


Chapas, L.C. 1961.
Plot size and reduction of variability in oil palm experiments.
Emp Jour. Exp. Agric., 29, 212-224.


Chaudhary, G.K.; Prajapati, B.H.; Patel, J.K.; Prajapti, R.I.; Loria, J.M. (2011)
Optimum size and shape of plot for field experiments on wheat under North Gujarat Condition.
J.Ind.Soci.Agril.S


CRI (1985).
Report of the Coconut Research Institute for 1985.
(Ed. R Mahindapala),  Lunuwila, Sri Lanka. 


Dutta, S. K., and HEATH, E. D.
Size, shape, and number of plots for field experiments with tea.
Not found.


Faqir Mohammad, Tariq Mahmood Bajwa; Sohail Ahmad. (2001).
Size and Shape of Plots for Wheat Yield Trials in Field Experiments.
International Journal Of Agriculture & Biology, 4, 397-402. 


Fisher, Alan Charles (1973).
A Technique for Designing Field Experiments Using Uniformity Trial Data.
North Carolina State University at Raleigh.
https://catalog.lib.ncsu.edu/catalog/NCSU508428
No electronic version.


French, M. H. (1956). 
Minimum size of experimental plots for the assessment of pasture yield.
East African Agr. and Forestry Res. Organ. Rpt. 1956.


French, M. H. 
Errores asociados con el uso de pequeñas parcelas de prueba en las evaluaciones de rendimiento de pastos. 
Agron. Trop. 10, 71-76.


Galal, H.E.; E.G.ttouh Abou. (1971).
Estimation of optimum plot size and shape for Egyptian cotton yield trials.
Alexandria Journal of Agricultural Research 19(2): 233-238


Gopini, D.D.; Kabaria, M.M. and Vaishnani, N.L. (1970).
Size and shape of plots in field experiments on groundnut.
Indian Journal of agricultural science, 40, 1004-1010.
Not found.


Gosh, G.L.M. & Sanyal, A.T. 1945.
Techniques of field experiments in jute.
Agri. Res. Memoire 4, Indian Central Jute Comm.


Gupta, J.P. and Raghavarao, D. (1969).
A uniformity trial on onions.
Journal of Indian Horticulture, 7, 184-187.


Gupta, S. C.; Kauchik, L. S.; Yadava T. P. (1991).
A study of size and shape of experimental plots with groundnut.
Indian Journal of Agricultural Research, 25, 161-166.
https://krishikosh.egranth.ac.in/handle/1/2040054
Restricted access.


Hamdi, A.; Shokr, E. M. H.; Sedhom, S. A.; Hassanein, S. A. A. (2003).
Estimation of optimum plot size and shape for lentil yield trials.
Egyptian Journal of Agricultural Research, 81, 1723-1734.


Handa, D.P., Sreenath, P.R., Sastry, J.A., Rajpal, S.K. and Shukla, N.P. (1982).
Size and shape of plots and blocks for experiments with oats grown for fodder.
Indian Journal of agricultural sciences, 52, 466-471.
Not found.


Hoshyar Chand Sharma (1991).
Some observations on estimation of plot size and shape, Bartlett's Rate Index and yield loss adjustments.
Journal of Indian potato Association, 18, 9-18.


Jayaram, K.; Venkataramu, M.N.; Sunderrajan, N.; Seetharam, A.
(1981)
Optimum size and shape of plots and blocks for field experiments in sunflower (Helianthus annuus Linn.)
Mysore Journal of Agricultural Sciences 15(4): 512-518
https://eurekamag.com/research/001/422/001422535.php


Joachim, A.W.R. 1935.
A uniformity trial with coconuts.
Trop. Agric. Mag. Ceylon. Agric. Soc. 85:198-207.
https://eurekamag.com/research/013/298/013298524.php
Not found.  Has data! Todo.


Jolly, A. L. 
Uniformity trials on estate cacao.
Trop. Agriculture, 19, 167-174.
https://journals.sta.uwi.edu/ta/index.asp?action=viewIssue&issueId=532
No access.


Kaushik, L.S.; Kapoor, K.; Hasija, R.C.; Tyagi, C.S. (1989).
A uniformity trial on moong (Vigna radiata (L) Wilczek)
Indian Journal of Agricultural Research 23(3): 138-142
https://krishikosh.egranth.ac.in/handle/1/2040100
Restricted access.


Khan, Mujahid. 2015.
Uniformity trial in raya (Brassica juncea).
M.Sc. Dissertation.
https://krishikosh.egranth.ac.in/handle/1/80362
Seems like paper should be here, but download fails.


Khurana, A., Rai, L. and Gupta, S.N. (1992).
A uniformity trial on soybean (Glycine max. L.).
Haryana agricultural University Journal of research, 22, 225-228.


Kristiensen, K. and Ersboll, A.K. 1995. 
The use of Geostatistical methods in variety trials, where some varieties are unreplicated. 
Biuletyn Oceny Odmain (Cultivar Testing Bulletin), 26-27, 113-122.
Not found.


Kumar, Manoj and Hasija (2002).
A study of size and shape of plots with wheat.
Annals of Agriculture Bio-research 7 (1), 89-93


Lakhera, M.L.; Singh, V.P.; Sundar, R. M. and Patel, N.M. (1995).
Optimum size and shape of plot for field experiments on gram.
Gujarat Agricultural University Research Journal, 21, 142-148.


Lakshmi, K. R. and Gadewar, A.U. (1989).
Optimum plot size for field trials with yams.
J. of Root Crops, 15, 25-27.


Lopes, S. J. et al. (2005).
Experimental plot size in grain sorghum in different plant densities. June 2005; Pesquisa Agropecuária Brasileira 40(6):525-530. 


Lu,  ChunTang et al (1995).
Estimation of optimum plot size and replicates number using data from rice uniformity trials.
J. of Agricultural Research of China, 44, 229-241.


Mahalanobis, P C; Chakravorti, S C; Banerjee, E A R. 1934.
Influence of shape and size of plots on the accuracy of field experiments with rice, Chinsurah, Bengal
Procedings of Indian Science Congress (Bombay) Sec Agricultural Statistics 21, 71.
http://hdl.handle.net/10263/1793
Not found; only contains abstract.


Mangat, N. S. (1984).
"Optimum size and shape of plot and block in cotton field experiments."
Journal of Research-Punjab Agricultural University (India).


McHatton, T.H. 1947.
The comparison of plot size in a peach experiment
Proceedings American Society Hort Science 49: 18-20
https://eurekamag.com/research/013/864/013864510.php
No access. Not found.


Menon, T.C.M. and Tyagi, B.N. (1971).
Optimum size and shape of plots in experiments with mandarin orange.
Indian Journal of agricultural science, 41, 857-861.
https://eurekamag.com/research/000/153/000153659.php
Not available.


Murray, D.B. 1950.
A uniformity trial with swamp rice.
Trop. Agriculture
https://journals.sta.uwi.edu/ta/index.asp?action=viewIssue&issueId=406
No access.


Pandya, H.R.; Upadhyay, S.M>; Parmar, B.A. (2006).
Analysis of uniformity trial on cotton.
J. Ind. Soc. Agric. Statist, 60, 175-236.


Peiris, W. V. D. and Salgado,  M. L. M. (1937).
Experimental error in field experiments with coconut. 
Trop. Agriculture, Trinidad, 89:75-85 


Pimentel Gomes, F. (1987).
Novos Aspectos do Tamanho Otimo das Parcelas em Experimentos Com Plantas Arbdreas (A New Contribution on  the Problem of Plot Size in Experiments with Trees).
Pesq. agropec. bras., Brasilia (in press).


Prabhakaran, P.V. (1974).
Optimum plot size for field experiments with tapioca
Agricultural Research Journal of Kerala, 12(1), 19-23.
http://krishikosh.egranth.ac.in/handle/1/5810114240


Rai, Lajpat Gupta, S.N. and Rai, L. (1994).
Optimum size and shape of plots in field experiments of soyabean (Glycine max. L.).
Annals of biology Ludhiana, 10, 261-263.


Rambabu; Aarwal, M.C.; Somaraj, P. and Chinnamani, S. (1980).
Size and shape of plots and blocks for field trials on natural grasslands in Nilgiris hills.
Indian Journal of agricultural science, 50, 598-602.
https://eurekamag.com/research/006/424/006424390.php
Not found


Schuster, W; Bretschneider-Hermann, N; Zschoche, K.-H. (1984).
Untersuchungen zur Feldversuchstechnik von Winterraps. Versuche zur Teilstückgrösse, Teilstückform und zur Zahl der Wiederholungen
[English: Investigations into experimental designs with winterrape experiments on plot size, plot-shape and numbers of replications].
Zeitschrift für Acker- und Pflanzenbau. [Eng: Journal of agronomy and crop science]. 1984, Vol 153, Num 6, pp 446-459.


Sen, A.R. 1963.
Some techniques of experimentation with cloval tea based on a uniformity trial.
Emp. J. Exp. Agri., 31, 296-310.


Sethi, A.S. (1985).
A modified approach to determine optimum size and shape of plots in field experiments on maize grown on terraced land.
Indian Journal of Agricultural Sciences, 36, 95-99.


Shamasundaran, K.S., Singh, K.P. and Mandhar, S.C. (2002).
Standardization of optimum size and shape of plots for gerbera under naturally ventilated greenhouse condition.
Indian Journal of Horticulture, 59, 431-434.
http://www.indianjournals.com/ijor.aspx?target=ijor:ijh&volume=59&issue=4&article=019
Paywall.


Shu, S.C.; Park, S.H.; Yu, I.S.; Joo, Y.J.; Hong, Y.K. (1970).
Studies on the optimum plot size, plot shape and number of replications in field experiments for wheat.
Research Reports of the Office of Rural Development, S. Korea, Crops, 13: 95-99
https://eurekamag.com/research/014/696/014696398.php


Singh, R.P. (1989).
Optimum plot size for yield trials on chillies
Indian Journal of Horticulture 46(3): 404-406
https://eurekamag.com/research/001/901/001901901.php


Sreenath, P.R. (1973).
Size and shape of plots and blocks in field trials with sorghum.
Indian Journal of Agricultural Sciences, 43, 110-112.
Not found.


Srinivasan, C.S.; George, M.V.; Subbalakshmi, V.; Amarnath, C.H. (1994).
Optimum plot size for field trials with Coffea arabica cv. Cauvery (Catimor)
Journal of Coffee Research 24(2): 87-96.


Upadhyay, S. M., Prajapati, B.H., Raja, K.R.V. and Darji, V.B. (1994).
Optimum plot size for summer paddy in the Navsari zone of Gujarat.
Gujarat Agricultural University Research Journal, 19, 92-97.
Not found.


Vaidyanathan, M.
The  method of covariance applicable to the utilization of the previous crop records for judging the improved precision of experiments.
Ind. J. Agric. Sci., 4, 327-42. 
Not found. Has data. Todo.


Weber, Charles Robert. 1941.
Statistical analysis of a uniformity trial of soybeans with reference to plot size and shape and a comparison of efficiency of various experimental designs.
Univ of Illinois. Thesis.


Webster, C. 1939.
A note on a uniformity trial with oil palms.
Tropical Agriculture, 16, 15-19.
https://journals.sta.uwi.edu/ojs/index.php/ta/article/view/5464
Behind paywall.


Yun, K.H.; Park, S.H.; Lee, Y.M. (1968).
An estimation of optimum plot size, shape and number of replications for yield performance trials of rice.
Res. Rep. Office rur. Dev, Suwon, 11: 1, 53-7. Bibl. 21
https://eurekamag.com/research/014/341/014341511.php


Zuhlke, Thomas Albert (1968).
Uniformity Trial in Pisum Sativum for Estimating Optimum Plot Size and Shape, Replication Number, and Relative Efficiency of Lattice Designs.
https://www.google.com/books/edition/A_Uniformity_Trial_in_Pisum_Sativum_for/Ya9nAAAAMAAJ?hl=en&gbpv=0

    
